package net.cmr.jurassicrevived.datagen;

import net.cmr.jurassicrevived.block.ModBlocks;
import net.cmr.jurassicrevived.item.ModItems;
import net.minecraft.data.recipes.RecipeCategory;
import net.minecraft.tags.ItemTags;
import net.minecraft.tags.TagKey;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.Items;
import net.minecraft.world.level.ItemLike;
import net.minecraft.world.level.block.Blocks;

import java.util.List;

public class ModRecipeProvider {

    public interface RecipeHelper {
        void buildShaped(RecipeCategory category, ItemLike result, int count, String[] patterns, Object... keys);
        void buildShapeless(RecipeCategory category, ItemLike result, int count, String name, ItemLike... ingredients);
        void buildSmelting(List<ItemLike> ingredients, RecipeCategory category, ItemLike result, float experience, int cookingTime, String group);
        void buildBlasting(List<ItemLike> ingredients, RecipeCategory category, ItemLike result, float experience, int cookingTime, String group);
        void buildSmelting(TagKey<Item> tag, RecipeCategory category, ItemLike result, float experience, int cookingTime, String group);
        void buildBlasting(TagKey<Item> tag, RecipeCategory category, ItemLike result, float experience, int cookingTime, String group);

        // Custom
        void dnaExtracting(ItemLike testTube, ItemLike tissue, ItemLike dna, int count);
        void dnaAnalyzing(ItemLike testTube, ItemLike material, ItemLike dna, int count);
        void dnaHybridizing(ItemLike result, int count, ItemLike... ingredients);
        void embryonicMachine(ItemLike syringe, ItemLike dna, ItemLike catalyst, ItemLike result, int count);
        void embryoCalcification(ItemLike syringe, ItemLike egg, ItemLike result, int count);
        void incubating(ItemLike egg, ItemLike result, int count);
        void fossilGrinding(ItemLike fossil, ItemLike tissue, int count);
        void skullToTissue(ItemLike skull, ItemLike tissue, int count);
        void fossilCleaning(ItemLike fossilBlock, ItemLike result, int count);
        
        // Special cases
		void amberRandomDNA(ItemLike testTube, ItemLike amber, ItemLike defaultDna, Object... weightedDnaAndCount);
	}

    public static void registerRecipes(RecipeHelper helper) {
        List<ItemLike> GYPSUM_COBBLESTONE_SMELTABLES = List.of(ModBlocks.GYPSUM_COBBLESTONE.get());
        helper.buildSmelting(GYPSUM_COBBLESTONE_SMELTABLES, RecipeCategory.MISC, ModBlocks.GYPSUM_STONE.get(), 0.25f, 200, "jr_gypsum_stone");
        helper.buildBlasting(GYPSUM_COBBLESTONE_SMELTABLES, RecipeCategory.MISC, ModBlocks.GYPSUM_STONE.get(), 0.25f, 100, "jr_gypsum_stone");

        List<ItemLike> GYPSUM_STONE_SMELTABLES = List.of(ModBlocks.GYPSUM_STONE.get());
        helper.buildSmelting(GYPSUM_STONE_SMELTABLES, RecipeCategory.MISC, ModBlocks.SMOOTH_GYPSUM_STONE.get(), 0.25f, 200, "jr_smooth_gypsum_stone");
        helper.buildBlasting(GYPSUM_STONE_SMELTABLES, RecipeCategory.MISC, ModBlocks.SMOOTH_GYPSUM_STONE.get(), 0.25f, 100, "jr_smooth_gypsum_stone");

        TagKey<Item> CHARRED_TERRACOTTA_SMELTABLES = ItemTags.TERRACOTTA;
        helper.buildSmelting(CHARRED_TERRACOTTA_SMELTABLES, RecipeCategory.MISC, ModBlocks.CHARRED_TERRACOTTA.get(), 0.25f, 200, "jr_charred_terracotta");
        helper.buildBlasting(CHARRED_TERRACOTTA_SMELTABLES, RecipeCategory.MISC, ModBlocks.CHARRED_TERRACOTTA.get(), 0.25f, 100, "jr_charred_terracotta");

        helper.buildShaped(RecipeCategory.MISC, ModBlocks.GYPSUM_BRICK_STAIRS.get(), 4, new String[]{"A  ", "AA ", "AAA"}, 'A', ModBlocks.GYPSUM_STONE_BRICKS.get());
        helper.buildShaped(RecipeCategory.MISC, ModBlocks.GYPSUM_BRICK_SLAB.get(), 6, new String[]{"AAA"}, 'A', ModBlocks.GYPSUM_STONE_BRICKS.get());
        helper.buildShaped(RecipeCategory.MISC, ModBlocks.GYPSUM_BRICK_WALL.get(), 6, new String[]{"AAA", "AAA"}, 'A', ModBlocks.GYPSUM_STONE_BRICKS.get());
        helper.buildShaped(RecipeCategory.MISC, ModBlocks.CHISELED_GYPSUM_STONE.get(), 1, new String[]{"A", "A"}, 'A', ModBlocks.GYPSUM_BRICK_SLAB.get());

        helper.buildShaped(RecipeCategory.MISC, ModBlocks.REINFORCED_BRICK_STAIRS.get(), 4, new String[]{"A  ", "AA ", "AAA"}, 'A', ModBlocks.REINFORCED_STONE_BRICKS.get());
        helper.buildShaped(RecipeCategory.MISC, ModBlocks.REINFORCED_BRICK_SLAB.get(), 6, new String[]{"AAA"}, 'A', ModBlocks.REINFORCED_STONE_BRICKS.get());
        helper.buildShaped(RecipeCategory.MISC, ModBlocks.REINFORCED_BRICK_WALL.get(), 6, new String[]{"AAA", "AAA"}, 'A', ModBlocks.REINFORCED_STONE_BRICKS.get());
        helper.buildShaped(RecipeCategory.MISC, ModBlocks.CHISELED_REINFORCED_STONE.get(), 1, new String[]{"A", "A"}, 'A', ModBlocks.REINFORCED_BRICK_SLAB.get());

		helper.buildShaped(RecipeCategory.MISC, ModBlocks.CHARRED_TERRACOTTA_STAIRS.get(), 4, new String[]{"A  ", "AA ", "AAA"}, 'A', ModBlocks.CHARRED_TERRACOTTA.get());
		helper.buildShaped(RecipeCategory.MISC, ModBlocks.CHARRED_TERRACOTTA_SLAB.get(), 6, new String[]{"AAA"}, 'A', ModBlocks.CHARRED_TERRACOTTA.get());
		helper.buildShaped(RecipeCategory.MISC, ModBlocks.CHARRED_TERRACOTTA_WALL.get(), 6, new String[]{"AAA", "AAA"}, 'A', ModBlocks.CHARRED_TERRACOTTA.get());

		helper.buildShaped(RecipeCategory.MISC, ModBlocks.GYPSUM_STONE_STAIRS.get(), 4, new String[]{"A  ", "AA ", "AAA"}, 'A', ModBlocks.GYPSUM_STONE.get());
		helper.buildShaped(RecipeCategory.MISC, ModBlocks.GYPSUM_STONE_SLAB.get(), 6, new String[]{"AAA"}, 'A', ModBlocks.GYPSUM_STONE.get());
		helper.buildShaped(RecipeCategory.MISC, ModBlocks.GYPSUM_STONE_WALL.get(), 6, new String[]{"AAA", "AAA"}, 'A', ModBlocks.GYPSUM_STONE.get());

		helper.buildShaped(RecipeCategory.MISC, ModBlocks.GYPSUM_COBBLESTONE_STAIRS.get(), 4, new String[]{"A  ", "AA ", "AAA"}, 'A', ModBlocks.GYPSUM_COBBLESTONE.get());
		helper.buildShaped(RecipeCategory.MISC, ModBlocks.GYPSUM_COBBLESTONE_SLAB.get(), 6, new String[]{"AAA"}, 'A', ModBlocks.GYPSUM_COBBLESTONE.get());
		helper.buildShaped(RecipeCategory.MISC, ModBlocks.GYPSUM_COBBLESTONE_WALL.get(), 6, new String[]{"AAA", "AAA"}, 'A', ModBlocks.GYPSUM_COBBLESTONE.get());

		helper.buildShaped(RecipeCategory.MISC, ModBlocks.SMOOTH_GYPSUM_STONE_STAIRS.get(), 4, new String[]{"A  ", "AA ", "AAA"}, 'A', ModBlocks.SMOOTH_GYPSUM_STONE.get());
		helper.buildShaped(RecipeCategory.MISC, ModBlocks.SMOOTH_GYPSUM_STONE_SLAB.get(), 6, new String[]{"AAA"}, 'A', ModBlocks.SMOOTH_GYPSUM_STONE.get());
		helper.buildShaped(RecipeCategory.MISC, ModBlocks.SMOOTH_GYPSUM_STONE_WALL.get(), 6, new String[]{"AAA", "AAA"}, 'A', ModBlocks.SMOOTH_GYPSUM_STONE.get());

		helper.buildShaped(RecipeCategory.MISC, ModBlocks.CHISELED_GYPSUM_STONE_STAIRS.get(), 4, new String[]{"A  ", "AA ", "AAA"}, 'A', ModBlocks.CHISELED_GYPSUM_STONE.get());
		helper.buildShaped(RecipeCategory.MISC, ModBlocks.CHISELED_GYPSUM_STONE_SLAB.get(), 6, new String[]{"AAA"}, 'A', ModBlocks.CHISELED_GYPSUM_STONE.get());
		helper.buildShaped(RecipeCategory.MISC, ModBlocks.CHISELED_GYPSUM_STONE_WALL.get(), 6, new String[]{"AAA", "AAA"}, 'A', ModBlocks.CHISELED_GYPSUM_STONE.get());

		helper.buildShaped(RecipeCategory.MISC, ModBlocks.REINFORCED_STONE_STAIRS.get(), 4, new String[]{"A  ", "AA ", "AAA"}, 'A', ModBlocks.REINFORCED_STONE.get());
		helper.buildShaped(RecipeCategory.MISC, ModBlocks.REINFORCED_STONE_SLAB.get(), 6, new String[]{"AAA"}, 'A', ModBlocks.REINFORCED_STONE.get());
		helper.buildShaped(RecipeCategory.MISC, ModBlocks.REINFORCED_STONE_WALL.get(), 6, new String[]{"AAA", "AAA"}, 'A', ModBlocks.REINFORCED_STONE.get());

		helper.buildShaped(RecipeCategory.MISC, ModBlocks.CHISELED_REINFORCED_STONE_STAIRS.get(), 4, new String[]{"A  ", "AA ", "AAA"}, 'A', ModBlocks.CHISELED_REINFORCED_STONE.get());
		helper.buildShaped(RecipeCategory.MISC, ModBlocks.CHISELED_REINFORCED_STONE_SLAB.get(), 6, new String[]{"AAA"}, 'A', ModBlocks.CHISELED_REINFORCED_STONE.get());
		helper.buildShaped(RecipeCategory.MISC, ModBlocks.CHISELED_REINFORCED_STONE_WALL.get(), 6, new String[]{"AAA", "AAA"}, 'A', ModBlocks.CHISELED_REINFORCED_STONE.get());

        helper.buildShaped(RecipeCategory.MISC, ModBlocks.TRASH_CAN.get(), 1, new String[]{"AAA", "A A", "AAA"}, 'A', Items.IRON_INGOT);
        helper.buildShaped(RecipeCategory.MISC, ModBlocks.BENCH.get(), 1, new String[]{"A  ", "AAA", "BBB"}, 'A', ItemTags.PLANKS, 'B', ModBlocks.REINFORCED_STONE_BRICKS.get());
        helper.buildShaped(RecipeCategory.MISC, ModBlocks.FENCE_LIGHT.get(), 1, new String[]{"A", "B"}, 'A', Blocks.GLOWSTONE, 'B', Items.IRON_INGOT);
        helper.buildShaped(RecipeCategory.MISC, ModBlocks.LIGHT_POST.get(), 1, new String[]{"A", "B"}, 'A', Blocks.GLOWSTONE, 'B', ModBlocks.GYPSUM_STONE.get());

        helper.buildShaped(RecipeCategory.MISC, ModBlocks.SANDSTONE_PATH.get(), 4, new String[]{"AA", "AA"}, 'A', Blocks.SANDSTONE);
        helper.buildShaped(RecipeCategory.MISC, ModBlocks.CHISELED_BRICK_PATH.get(), 4, new String[]{"AA", "AA"}, 'A', Blocks.BRICKS);
        helper.buildShaped(RecipeCategory.MISC, ModBlocks.CONCRETE_PATH.get(), 4, new String[]{"AA", "AA"}, 'A', Blocks.GRAY_CONCRETE);
        helper.buildShaped(RecipeCategory.MISC, ModBlocks.LIGHT_GRAY_TERRACOTTA_PATH.get(), 4, new String[]{"AA", "AA"}, 'A', Blocks.LIGHT_GRAY_TERRACOTTA);

        helper.buildShaped(RecipeCategory.MISC, ModItems.TEST_TUBE.get(), 3, new String[]{"  A", " B ", "B  "}, 'A', Items.IRON_INGOT, 'B', Blocks.GLASS);
        helper.buildShaped(RecipeCategory.MISC, ModItems.SYRINGE.get(), 3, new String[]{"  A", " B ", "C  "}, 'A', Items.IRON_INGOT, 'B', Blocks.GLASS, 'C', Items.IRON_NUGGET);
        helper.buildShaped(RecipeCategory.MISC, ModItems.CABLE.get(), 4, new String[]{" BA", "BAB", "AB "}, 'A', Items.COPPER_INGOT, 'B', Items.IRON_NUGGET);
        helper.buildShaped(RecipeCategory.MISC, ModItems.SCREEN.get(), 2, new String[]{"ABA", "ABA", " C "}, 'A', Items.IRON_INGOT, 'B', Blocks.REDSTONE_LAMP, 'C', ModItems.CABLE.get());
        helper.buildShaped(RecipeCategory.MISC, ModItems.PROCESSOR.get(), 1, new String[]{"ABA", "BCB", "ABA"}, 'A', Items.GOLD_NUGGET, 'B', Items.IRON_INGOT, 'C', Items.REDSTONE);
        helper.buildShaped(RecipeCategory.MISC, ModItems.TIRE.get(), 1, new String[]{"AAA", "ABA", "AAA"}, 'A', Items.INK_SAC, 'B', Items.IRON_INGOT);
        helper.buildShaped(RecipeCategory.MISC, ModItems.CUTTING_BLADES.get(), 4, new String[]{"A A", " A ", "A A"}, 'A', Items.IRON_INGOT);

        helper.buildShaped(RecipeCategory.MISC, ModBlocks.GYPSUM_STONE_BRICKS.get(), 4, new String[]{"AA", "AA"}, 'A', ModBlocks.GYPSUM_STONE.get());
        helper.buildShaped(RecipeCategory.MISC, ModBlocks.REINFORCED_STONE.get(), 6, new String[]{"AAA", "AAA", "AAA"}, 'A', Blocks.STONE);
        helper.buildShaped(RecipeCategory.MISC, ModBlocks.REINFORCED_STONE_BRICKS.get(), 6, new String[]{"AAA", "AAA", "AAA"}, 'A', Blocks.STONE_BRICKS);

        helper.buildShaped(RecipeCategory.MISC, ModBlocks.LOW_SECURITY_FENCE_POLE.get(), 8, new String[]{"ABA", " B ", "ABA"}, 'A', Items.IRON_NUGGET, 'B', Items.IRON_INGOT);
        helper.buildShaped(RecipeCategory.MISC, ModBlocks.LOW_SECURITY_FENCE_WIRE.get(), 16, new String[]{"AAA", " B ", "AAA"}, 'A', Items.IRON_INGOT, 'B', Items.REDSTONE);
        helper.buildShaped(RecipeCategory.MISC, ModBlocks.MEDIUM_SECURITY_FENCE_POLE.get(), 8, new String[]{"ABA", "ABA", "ABA"}, 'A', Items.IRON_INGOT, 'B', Items.IRON_NUGGET);
        helper.buildShaped(RecipeCategory.MISC, ModBlocks.MEDIUM_SECURITY_FENCE_WIRE.get(), 16, new String[]{"AAA", "BBB", "AAA"}, 'A', Items.IRON_INGOT, 'B', Items.REDSTONE);

        helper.buildShaped(RecipeCategory.MISC, ModBlocks.TANK.get(), 1, new String[]{"AAA", "ABA", "AAA"}, 'A', Items.IRON_INGOT, 'B', Items.BUCKET);
        helper.buildShaped(RecipeCategory.MISC, ModBlocks.POWER_CELL.get(), 1, new String[]{"AAA", "ABA", "AAA"}, 'A', Items.IRON_INGOT, 'B', ModBlocks.POWER_PIPE.get());
        helper.buildShaped(RecipeCategory.MISC, ModBlocks.WOOD_CRATE.get(), 1, new String[]{"AAA", "ABA", "AAA"}, 'A', ItemTags.PLANKS, 'B', Blocks.CHEST);
        helper.buildShaped(RecipeCategory.MISC, ModBlocks.IRON_CRATE.get(), 1, new String[]{"AAA", "ABA", "AAA"}, 'A', Items.IRON_INGOT, 'B', Blocks.CHEST);
        helper.buildShaped(RecipeCategory.MISC, ModBlocks.CAT_PLUSHIE.get(), 1, new String[]{"ABA", "CBD", "BBA"}, 'A', Blocks.BLACK_WOOL, 'B', Blocks.WHITE_WOOL, 'C', Blocks.GREEN_WOOL, 'D', Blocks.GRAY_WOOL);

        helper.buildShaped(RecipeCategory.MISC, ModBlocks.GENERATOR.get(), 1, new String[]{"ABA", "CDE", "ABA"}, 'A', Blocks.IRON_BLOCK, 'B', ModItems.CABLE.get(), 'C', Blocks.REDSTONE_BLOCK, 'D', ModItems.PROCESSOR.get(), 'E', Items.COPPER_INGOT);
        helper.buildShaped(RecipeCategory.MISC, ModBlocks.DNA_EXTRACTOR.get(), 1, new String[]{"AAA", "BCD", "AAA"}, 'A', Items.LAPIS_LAZULI, 'B', ModItems.SCREEN.get(), 'C', ModItems.CABLE.get(), 'D', ModItems.PROCESSOR.get());
        helper.buildShaped(RecipeCategory.MISC, ModBlocks.DNA_ANALYZER.get(), 1, new String[]{"AAA", "BCD", "EEE"}, 'A', ModItems.TEST_TUBE.get(), 'B', ModItems.SCREEN.get(), 'C', ModItems.CABLE.get(), 'D', ModItems.PROCESSOR.get(), 'E', ModItems.SYRINGE.get());
        helper.buildShaped(RecipeCategory.MISC, ModBlocks.FOSSIL_GRINDER.get(), 1, new String[]{"ABA", "CDC", "AEA"}, 'A', Items.IRON_INGOT, 'B', Blocks.GLASS, 'C', Items.LAPIS_LAZULI, 'D', ModItems.CUTTING_BLADES.get(), 'E', Items.WATER_BUCKET);
        helper.buildShaped(RecipeCategory.MISC, ModBlocks.FOSSIL_CLEANER.get(), 1, new String[]{"ABA", "ACA", "AAA"}, 'A', Items.IRON_INGOT, 'B', Items.IRON_NUGGET, 'C', Blocks.GLASS);
        helper.buildShaped(RecipeCategory.MISC, ModBlocks.DNA_HYBRIDIZER.get(), 1, new String[]{"ABA", "CDC", "BEB"}, 'A', ModItems.SCREEN.get(), 'B', Items.IRON_INGOT, 'C', ModItems.CABLE.get(), 'D', ModItems.PROCESSOR.get(), 'E', Items.REDSTONE);
        helper.buildShaped(RecipeCategory.MISC, ModBlocks.EMBRYONIC_MACHINE.get(), 1, new String[]{"AAA", "BCB", "ADA"}, 'A', Items.IRON_INGOT, 'B', ModItems.TEST_TUBE.get(), 'C', Items.IRON_NUGGET, 'D', Items.REDSTONE);
        helper.buildShaped(RecipeCategory.MISC, ModBlocks.EMBRYO_CALCIFICATION_MACHINE.get(), 1, new String[]{"AB ", "CDE", "FAF"}, 'A', Items.IRON_INGOT, 'B', ModItems.SYRINGE.get(), 'C', ModItems.SCREEN.get(), 'D', ModItems.CABLE.get(), 'E', ModItems.PROCESSOR.get(), 'F', Items.FLINT);
        helper.buildShaped(RecipeCategory.MISC, ModBlocks.INCUBATOR.get(), 1, new String[]{"AAA", "BCB", "DED"}, 'A', Blocks.GLASS, 'B', Items.COPPER_INGOT, 'C', Blocks.HAY_BLOCK, 'D', Items.IRON_INGOT, 'E', ModItems.CABLE.get());
        helper.buildShaped(RecipeCategory.MISC, ModItems.WRENCH.get(), 1, new String[]{" A ", " BA", "B  "}, 'A', Items.IRON_INGOT, 'B', Items.IRON_NUGGET);
        helper.buildShaped(RecipeCategory.MISC, ModBlocks.ITEM_PIPE.get(), 8, new String[]{"AAA"}, 'A', ModItems.CABLE.get());
        helper.buildShaped(RecipeCategory.MISC, ModBlocks.FLUID_PIPE.get(), 8, new String[]{" A ", "BBB", " A "}, 'A', Items.WATER_BUCKET, 'B', ModItems.CABLE.get());
        helper.buildShaped(RecipeCategory.MISC, ModBlocks.POWER_PIPE.get(), 8, new String[]{" A ", "BBB", " A "}, 'A', Items.REDSTONE, 'B', ModItems.CABLE.get());

        helper.buildShapeless(RecipeCategory.MISC, ModBlocks.WHITE_GENERATOR.get(), 1, "white_generator_from_generator", ModBlocks.GENERATOR.get());
        helper.buildShapeless(RecipeCategory.MISC, ModBlocks.GENERATOR.get(), 1, "generator_from_white_generator", ModBlocks.WHITE_GENERATOR.get());
        helper.buildShapeless(RecipeCategory.MISC, ModBlocks.WHITE_DNA_EXTRACTOR.get(), 1, "white_dna_extractor_from_dna_extractor", ModBlocks.DNA_EXTRACTOR.get());
        helper.buildShapeless(RecipeCategory.MISC, ModBlocks.DNA_EXTRACTOR.get(), 1, "dna_extractor_from_white_dna_extractor", ModBlocks.WHITE_DNA_EXTRACTOR.get());
        helper.buildShapeless(RecipeCategory.MISC, ModBlocks.WHITE_DNA_ANALYZER.get(), 1, "white_dna_analyzer_from_dna_analyzer", ModBlocks.DNA_ANALYZER.get());
        helper.buildShapeless(RecipeCategory.MISC, ModBlocks.DNA_ANALYZER.get(), 1, "dna_analyzer_from_white_dna_analyzer", ModBlocks.WHITE_DNA_ANALYZER.get());
        helper.buildShapeless(RecipeCategory.MISC, ModBlocks.WHITE_FOSSIL_GRINDER.get(), 1, "white_fossil_grinder_from_fossil_grinder", ModBlocks.FOSSIL_GRINDER.get());
        helper.buildShapeless(RecipeCategory.MISC, ModBlocks.FOSSIL_GRINDER.get(), 1, "fossil_grinder_from_white_fossil_grinder", ModBlocks.WHITE_FOSSIL_GRINDER.get());
        helper.buildShapeless(RecipeCategory.MISC, ModBlocks.WHITE_FOSSIL_CLEANER.get(), 1, "white_fossil_cleaner_from_fossil_cleaner", ModBlocks.FOSSIL_CLEANER.get());
        helper.buildShapeless(RecipeCategory.MISC, ModBlocks.FOSSIL_CLEANER.get(), 1, "fossil_cleaner_from_white_fossil_cleaner", ModBlocks.WHITE_FOSSIL_CLEANER.get());
        helper.buildShapeless(RecipeCategory.MISC, ModBlocks.WHITE_DNA_HYBRIDIZER.get(), 1, "white_dna_hybridizer_from_dna_hybridizer", ModBlocks.DNA_HYBRIDIZER.get());
        helper.buildShapeless(RecipeCategory.MISC, ModBlocks.DNA_HYBRIDIZER.get(), 1, "dna_hybridizer_from_white_dna_hybridizer", ModBlocks.WHITE_DNA_HYBRIDIZER.get());
        helper.buildShapeless(RecipeCategory.MISC, ModBlocks.WHITE_EMBRYONIC_MACHINE.get(), 1, "white_embryonic_machine_from_embryonic_machine", ModBlocks.EMBRYONIC_MACHINE.get());
        helper.buildShapeless(RecipeCategory.MISC, ModBlocks.EMBRYONIC_MACHINE.get(), 1, "embryonic_machine_from_white_embryonic_machine", ModBlocks.WHITE_EMBRYONIC_MACHINE.get());
        helper.buildShapeless(RecipeCategory.MISC, ModBlocks.WHITE_EMBRYO_CALCIFICATION_MACHINE.get(), 1, "white_embryo_calcification_machine_from_embryo_calcification_machine", ModBlocks.EMBRYO_CALCIFICATION_MACHINE.get());
        helper.buildShapeless(RecipeCategory.MISC, ModBlocks.EMBRYO_CALCIFICATION_MACHINE.get(), 1, "embryo_calcification_machine_from_white_embryo_calcification_machine", ModBlocks.WHITE_EMBRYO_CALCIFICATION_MACHINE.get());
        helper.buildShapeless(RecipeCategory.MISC, ModBlocks.WHITE_INCUBATOR.get(), 1, "white_incubator_from_incubator", ModBlocks.INCUBATOR.get());
        helper.buildShapeless(RecipeCategory.MISC, ModBlocks.INCUBATOR.get(), 1, "incubator_from_white_incubator", ModBlocks.WHITE_INCUBATOR.get());

        helper.dnaExtracting(ModItems.TEST_TUBE.get(), ModItems.APATOSAURUS_TISSUE.get(), ModItems.APATOSAURUS_DNA.get(), 1);
        helper.dnaExtracting(ModItems.TEST_TUBE.get(), ModItems.ALBERTOSAURUS_TISSUE.get(), ModItems.ALBERTOSAURUS_DNA.get(), 1);
        helper.dnaExtracting(ModItems.TEST_TUBE.get(), ModItems.BRACHIOSAURUS_TISSUE.get(), ModItems.BRACHIOSAURUS_DNA.get(), 1);
        helper.dnaExtracting(ModItems.TEST_TUBE.get(), ModItems.CERATOSAURUS_TISSUE.get(), ModItems.CERATOSAURUS_DNA.get(), 1);
        helper.dnaExtracting(ModItems.TEST_TUBE.get(), ModItems.COMPSOGNATHUS_TISSUE.get(), ModItems.COMPSOGNATHUS_DNA.get(), 1);
        helper.dnaExtracting(ModItems.TEST_TUBE.get(), ModItems.DILOPHOSAURUS_TISSUE.get(), ModItems.DILOPHOSAURUS_DNA.get(), 1);
        helper.dnaExtracting(ModItems.TEST_TUBE.get(), ModItems.DIPLODOCUS_TISSUE.get(), ModItems.DIPLODOCUS_DNA.get(), 1);
        helper.dnaExtracting(ModItems.TEST_TUBE.get(), ModItems.GALLIMIMUS_TISSUE.get(), ModItems.GALLIMIMUS_DNA.get(), 1);
        helper.dnaExtracting(ModItems.TEST_TUBE.get(), ModItems.INDOMINUS_REX_TISSUE.get(), ModItems.INDOMINUS_REX_DNA.get(), 1);
        helper.dnaExtracting(ModItems.TEST_TUBE.get(), ModItems.OURANOSAURUS_TISSUE.get(), ModItems.OURANOSAURUS_DNA.get(), 1);
        helper.dnaExtracting(ModItems.TEST_TUBE.get(), ModItems.PARASAUROLOPHUS_TISSUE.get(), ModItems.PARASAUROLOPHUS_DNA.get(), 1);
        helper.dnaExtracting(ModItems.TEST_TUBE.get(), ModItems.SPINOSAURUS_TISSUE.get(), ModItems.SPINOSAURUS_DNA.get(), 1);
        helper.dnaExtracting(ModItems.TEST_TUBE.get(), ModItems.TRICERATOPS_TISSUE.get(), ModItems.TRICERATOPS_DNA.get(), 1);
        helper.dnaExtracting(ModItems.TEST_TUBE.get(), ModItems.TYRANNOSAURUS_REX_TISSUE.get(), ModItems.TYRANNOSAURUS_REX_DNA.get(), 1);
        helper.dnaExtracting(ModItems.TEST_TUBE.get(), ModItems.VELOCIRAPTOR_TISSUE.get(), ModItems.VELOCIRAPTOR_DNA.get(), 1);
        helper.dnaExtracting(ModItems.TEST_TUBE.get(), ModItems.BARYONYX_TISSUE.get(), ModItems.BARYONYX_DNA.get(), 1);
        helper.dnaExtracting(ModItems.TEST_TUBE.get(), ModItems.CARNOTAURUS_TISSUE.get(), ModItems.CARNOTAURUS_DNA.get(), 1);
        helper.dnaExtracting(ModItems.TEST_TUBE.get(), ModItems.CONCAVENATOR_TISSUE.get(), ModItems.CONCAVENATOR_DNA.get(), 1);
        helper.dnaExtracting(ModItems.TEST_TUBE.get(), ModItems.DEINONYCHUS_TISSUE.get(), ModItems.DEINONYCHUS_DNA.get(), 1);
        helper.dnaExtracting(ModItems.TEST_TUBE.get(), ModItems.EDMONTOSAURUS_TISSUE.get(), ModItems.EDMONTOSAURUS_DNA.get(), 1);
        helper.dnaExtracting(ModItems.TEST_TUBE.get(), ModItems.GIGANOTOSAURUS_TISSUE.get(), ModItems.GIGANOTOSAURUS_DNA.get(), 1);
        helper.dnaExtracting(ModItems.TEST_TUBE.get(), ModItems.GUANLONG_TISSUE.get(), ModItems.GUANLONG_DNA.get(), 1);
        helper.dnaExtracting(ModItems.TEST_TUBE.get(), ModItems.HERRERASAURUS_TISSUE.get(), ModItems.HERRERASAURUS_DNA.get(), 1);
        helper.dnaExtracting(ModItems.TEST_TUBE.get(), ModItems.MAJUNGASAURUS_TISSUE.get(), ModItems.MAJUNGASAURUS_DNA.get(), 1);
        helper.dnaExtracting(ModItems.TEST_TUBE.get(), ModItems.PROCOMPSOGNATHUS_TISSUE.get(), ModItems.PROCOMPSOGNATHUS_DNA.get(), 1);
        helper.dnaExtracting(ModItems.TEST_TUBE.get(), ModItems.PROTOCERATOPS_TISSUE.get(), ModItems.PROTOCERATOPS_DNA.get(), 1);
        helper.dnaExtracting(ModItems.TEST_TUBE.get(), ModItems.RUGOPS_TISSUE.get(), ModItems.RUGOPS_DNA.get(), 1);
        helper.dnaExtracting(ModItems.TEST_TUBE.get(), ModItems.SHANTUNGOSAURUS_TISSUE.get(), ModItems.SHANTUNGOSAURUS_DNA.get(), 1);
        helper.dnaExtracting(ModItems.TEST_TUBE.get(), ModItems.STEGOSAURUS_TISSUE.get(), ModItems.STEGOSAURUS_DNA.get(), 1);
        helper.dnaExtracting(ModItems.TEST_TUBE.get(), ModItems.STYRACOSAURUS_TISSUE.get(), ModItems.STYRACOSAURUS_DNA.get(), 1);
        helper.dnaExtracting(ModItems.TEST_TUBE.get(), ModItems.THERIZINOSAURUS_TISSUE.get(), ModItems.THERIZINOSAURUS_DNA.get(), 1);
        helper.dnaExtracting(ModItems.TEST_TUBE.get(), ModItems.DISTORTUS_REX_TISSUE.get(), ModItems.DISTORTUS_REX_DNA.get(), 1);
        helper.dnaExtracting(ModItems.TEST_TUBE.get(), ModItems.ALLOSAURUS_TISSUE.get(), ModItems.ALLOSAURUS_DNA.get(), 1);
        helper.dnaExtracting(ModItems.TEST_TUBE.get(), ModItems.ALVAREZSAURUS_TISSUE.get(), ModItems.ALVAREZSAURUS_DNA.get(), 1);
        helper.dnaExtracting(ModItems.TEST_TUBE.get(), ModItems.ANKYLOSAURUS_TISSUE.get(), ModItems.ANKYLOSAURUS_DNA.get(), 1);
        helper.dnaExtracting(ModItems.TEST_TUBE.get(), ModItems.ARAMBOURGIANIA_TISSUE.get(), ModItems.ARAMBOURGIANIA_DNA.get(), 1);
        helper.dnaExtracting(ModItems.TEST_TUBE.get(), ModItems.CARCHARODONTOSAURUS_TISSUE.get(), ModItems.CARCHARODONTOSAURUS_DNA.get(), 1);
        helper.dnaExtracting(ModItems.TEST_TUBE.get(), ModItems.CEARADACTYLUS_TISSUE.get(), ModItems.CEARADACTYLUS_DNA.get(), 1);
        helper.dnaExtracting(ModItems.TEST_TUBE.get(), ModItems.CHASMOSAURUS_TISSUE.get(), ModItems.CHASMOSAURUS_DNA.get(), 1);
        helper.dnaExtracting(ModItems.TEST_TUBE.get(), ModItems.COELOPHYSIS_TISSUE.get(), ModItems.COELOPHYSIS_DNA.get(), 1);
        helper.dnaExtracting(ModItems.TEST_TUBE.get(), ModItems.COELURUS_TISSUE.get(), ModItems.COELURUS_DNA.get(), 1);
        helper.dnaExtracting(ModItems.TEST_TUBE.get(), ModItems.CORYTHOSAURUS_TISSUE.get(), ModItems.CORYTHOSAURUS_DNA.get(), 1);
        helper.dnaExtracting(ModItems.TEST_TUBE.get(), ModItems.DIMORPHODON_TISSUE.get(), ModItems.DIMORPHODON_DNA.get(), 1);
        helper.dnaExtracting(ModItems.TEST_TUBE.get(), ModItems.DRYOSAURUS_TISSUE.get(), ModItems.DRYOSAURUS_DNA.get(), 1);
        helper.dnaExtracting(ModItems.TEST_TUBE.get(), ModItems.GEOSTERNBERGIA_TISSUE.get(), ModItems.GEOSTERNBERGIA_DNA.get(), 1);
        helper.dnaExtracting(ModItems.TEST_TUBE.get(), ModItems.GUIDRACO_TISSUE.get(), ModItems.GUIDRACO_DNA.get(), 1);
        helper.dnaExtracting(ModItems.TEST_TUBE.get(), ModItems.HADROSAURUS_TISSUE.get(), ModItems.HADROSAURUS_DNA.get(), 1);
        helper.dnaExtracting(ModItems.TEST_TUBE.get(), ModItems.HYPSILOPHODON_TISSUE.get(), ModItems.HYPSILOPHODON_DNA.get(), 1);
        helper.dnaExtracting(ModItems.TEST_TUBE.get(), ModItems.INDORAPTOR_TISSUE.get(), ModItems.INDORAPTOR_DNA.get(), 1);
        helper.dnaExtracting(ModItems.TEST_TUBE.get(), ModItems.INOSTRANCEVIA_TISSUE.get(), ModItems.INOSTRANCEVIA_DNA.get(), 1);
        helper.dnaExtracting(ModItems.TEST_TUBE.get(), ModItems.LAMBEOSAURUS_TISSUE.get(), ModItems.LAMBEOSAURUS_DNA.get(), 1);
        helper.dnaExtracting(ModItems.TEST_TUBE.get(), ModItems.LUDODACTYLUS_TISSUE.get(), ModItems.LUDODACTYLUS_DNA.get(), 1);
        helper.dnaExtracting(ModItems.TEST_TUBE.get(), ModItems.MAMENCHISAURUS_TISSUE.get(), ModItems.MAMENCHISAURUS_DNA.get(), 1);
        helper.dnaExtracting(ModItems.TEST_TUBE.get(), ModItems.METRIACANTHOSAURUS_TISSUE.get(), ModItems.METRIACANTHOSAURUS_DNA.get(), 1);
        helper.dnaExtracting(ModItems.TEST_TUBE.get(), ModItems.MOGANOPTERUS_TISSUE.get(), ModItems.MOGANOPTERUS_DNA.get(), 1);
        helper.dnaExtracting(ModItems.TEST_TUBE.get(), ModItems.NYCTOSAURUS_TISSUE.get(), ModItems.NYCTOSAURUS_DNA.get(), 1);
        helper.dnaExtracting(ModItems.TEST_TUBE.get(), ModItems.ORNITHOLESTES_TISSUE.get(), ModItems.ORNITHOLESTES_DNA.get(), 1);
        helper.dnaExtracting(ModItems.TEST_TUBE.get(), ModItems.ORNITHOMIMUS_TISSUE.get(), ModItems.ORNITHOMIMUS_DNA.get(), 1);
        helper.dnaExtracting(ModItems.TEST_TUBE.get(), ModItems.OVIRAPTOR_TISSUE.get(), ModItems.OVIRAPTOR_DNA.get(), 1);
        helper.dnaExtracting(ModItems.TEST_TUBE.get(), ModItems.PACHYCEPHALOSAURUS_TISSUE.get(), ModItems.PACHYCEPHALOSAURUS_DNA.get(), 1);
        helper.dnaExtracting(ModItems.TEST_TUBE.get(), ModItems.PROCERATOSAURUS_TISSUE.get(), ModItems.PROCERATOSAURUS_DNA.get(), 1);
        helper.dnaExtracting(ModItems.TEST_TUBE.get(), ModItems.PTERANODON_TISSUE.get(), ModItems.PTERANODON_DNA.get(), 1);
        helper.dnaExtracting(ModItems.TEST_TUBE.get(), ModItems.PTERODAUSTRO_TISSUE.get(), ModItems.PTERODAUSTRO_DNA.get(), 1);
        helper.dnaExtracting(ModItems.TEST_TUBE.get(), ModItems.QUETZALCOATLUS_TISSUE.get(), ModItems.QUETZALCOATLUS_DNA.get(), 1);
        helper.dnaExtracting(ModItems.TEST_TUBE.get(), ModItems.RAJASAURUS_TISSUE.get(), ModItems.RAJASAURUS_DNA.get(), 1);
        helper.dnaExtracting(ModItems.TEST_TUBE.get(), ModItems.SEGISAURUS_TISSUE.get(), ModItems.SEGISAURUS_DNA.get(), 1);
        helper.dnaExtracting(ModItems.TEST_TUBE.get(), ModItems.TAPEJARA_TISSUE.get(), ModItems.TAPEJARA_DNA.get(), 1);
        helper.dnaExtracting(ModItems.TEST_TUBE.get(), ModItems.TITANOSAURUS_TISSUE.get(), ModItems.TITANOSAURUS_DNA.get(), 1);
        helper.dnaExtracting(ModItems.TEST_TUBE.get(), ModItems.TROODON_TISSUE.get(), ModItems.TROODON_DNA.get(), 1);
        helper.dnaExtracting(ModItems.TEST_TUBE.get(), ModItems.TROPEOGNATHUS_TISSUE.get(), ModItems.TROPEOGNATHUS_DNA.get(), 1);
        helper.dnaExtracting(ModItems.TEST_TUBE.get(), ModItems.TUPUXUARA_TISSUE.get(), ModItems.TUPUXUARA_DNA.get(), 1);
        helper.dnaExtracting(ModItems.TEST_TUBE.get(), ModItems.UTAHRAPTOR_TISSUE.get(), ModItems.UTAHRAPTOR_DNA.get(), 1);
        helper.dnaExtracting(ModItems.TEST_TUBE.get(), ModItems.ZHENYUANOPTERUS_TISSUE.get(), ModItems.ZHENYUANOPTERUS_DNA.get(), 1);
        helper.dnaExtracting(ModItems.TEST_TUBE.get(), ModItems.ACHILLOBATOR_TISSUE.get(), ModItems.ACHILLOBATOR_DNA.get(), 1);
        helper.dnaExtracting(ModItems.TEST_TUBE.get(), ModItems.SUCHOMIMUS_TISSUE.get(), ModItems.SUCHOMIMUS_DNA.get(), 1);
        helper.dnaExtracting(ModItems.TEST_TUBE.get(), ModItems.CHILESAURUS_TISSUE.get(), ModItems.CHILESAURUS_DNA.get(), 1);
        helper.dnaExtracting(ModItems.TEST_TUBE.get(), ModItems.THESCELOSAURUS_TISSUE.get(), ModItems.THESCELOSAURUS_DNA.get(), 1);
        helper.dnaExtracting(ModItems.TEST_TUBE.get(), ModItems.MUSSASAURUS_TISSUE.get(), ModItems.MUSSASAURUS_DNA.get(), 1);

        helper.fossilCleaning(ModBlocks.STONE_FOSSIL.get(), ModItems.APATOSAURUS_SKULL_FOSSIL.get(), 1);
        helper.fossilCleaning(ModBlocks.DEEPSLATE_FOSSIL.get(), ModItems.VELOCIRAPTOR_SKULL_FOSSIL.get(), 1);

		helper.fossilGrinding(ModItems.ALBERTOSAURUS_SKULL_FOSSIL.get(), ModItems.ALBERTOSAURUS_TISSUE.get(), 1);
		helper.fossilGrinding(ModItems.APATOSAURUS_SKULL_FOSSIL.get(), ModItems.APATOSAURUS_TISSUE.get(), 1);
		helper.fossilGrinding(ModItems.BRACHIOSAURUS_SKULL_FOSSIL.get(), ModItems.BRACHIOSAURUS_TISSUE.get(), 1);
		helper.fossilGrinding(ModItems.CERATOSAURUS_SKULL_FOSSIL.get(), ModItems.CERATOSAURUS_TISSUE.get(), 1);
		helper.fossilGrinding(ModItems.COMPSOGNATHUS_SKULL_FOSSIL.get(), ModItems.COMPSOGNATHUS_TISSUE.get(), 1);
		helper.fossilGrinding(ModItems.DILOPHOSAURUS_SKULL_FOSSIL.get(), ModItems.DILOPHOSAURUS_TISSUE.get(), 1);
		helper.fossilGrinding(ModItems.DIPLODOCUS_SKULL_FOSSIL.get(), ModItems.DIPLODOCUS_TISSUE.get(), 1);
		helper.fossilGrinding(ModItems.GALLIMIMUS_SKULL_FOSSIL.get(), ModItems.GALLIMIMUS_TISSUE.get(), 1);
		helper.fossilGrinding(ModItems.OURANOSAURUS_SKULL_FOSSIL.get(), ModItems.OURANOSAURUS_TISSUE.get(), 1);
		helper.fossilGrinding(ModItems.PARASAUROLOPHUS_SKULL_FOSSIL.get(), ModItems.PARASAUROLOPHUS_TISSUE.get(), 1);
		helper.fossilGrinding(ModItems.SPINOSAURUS_SKULL_FOSSIL.get(), ModItems.SPINOSAURUS_TISSUE.get(), 1);
		helper.fossilGrinding(ModItems.TRICERATOPS_SKULL_FOSSIL.get(), ModItems.TRICERATOPS_TISSUE.get(), 1);
		helper.fossilGrinding(ModItems.TYRANNOSAURUS_REX_SKULL_FOSSIL.get(), ModItems.TYRANNOSAURUS_REX_TISSUE.get(), 1);
		helper.fossilGrinding(ModItems.VELOCIRAPTOR_SKULL_FOSSIL.get(), ModItems.VELOCIRAPTOR_TISSUE.get(), 1);
		helper.fossilGrinding(ModItems.BARYONYX_SKULL_FOSSIL.get(), ModItems.BARYONYX_TISSUE.get(), 1);
		helper.fossilGrinding(ModItems.CARNOTAURUS_SKULL_FOSSIL.get(), ModItems.CARNOTAURUS_TISSUE.get(), 1);
		helper.fossilGrinding(ModItems.CONCAVENATOR_SKULL_FOSSIL.get(), ModItems.CONCAVENATOR_TISSUE.get(), 1);
		helper.fossilGrinding(ModItems.DEINONYCHUS_SKULL_FOSSIL.get(), ModItems.DEINONYCHUS_TISSUE.get(), 1);
		helper.fossilGrinding(ModItems.EDMONTOSAURUS_SKULL_FOSSIL.get(), ModItems.EDMONTOSAURUS_TISSUE.get(), 1);
		helper.fossilGrinding(ModItems.GIGANOTOSAURUS_SKULL_FOSSIL.get(), ModItems.GIGANOTOSAURUS_TISSUE.get(), 1);
		helper.fossilGrinding(ModItems.GUANLONG_SKULL_FOSSIL.get(), ModItems.GUANLONG_TISSUE.get(), 1);
		helper.fossilGrinding(ModItems.HERRERASAURUS_SKULL_FOSSIL.get(), ModItems.HERRERASAURUS_TISSUE.get(), 1);
		helper.fossilGrinding(ModItems.MAJUNGASAURUS_SKULL_FOSSIL.get(), ModItems.MAJUNGASAURUS_TISSUE.get(), 1);
		helper.fossilGrinding(ModItems.PROCOMPSOGNATHUS_SKULL_FOSSIL.get(), ModItems.PROCOMPSOGNATHUS_TISSUE.get(), 1);
		helper.fossilGrinding(ModItems.PROTOCERATOPS_SKULL_FOSSIL.get(), ModItems.PROTOCERATOPS_TISSUE.get(), 1);
		helper.fossilGrinding(ModItems.RUGOPS_SKULL_FOSSIL.get(), ModItems.RUGOPS_TISSUE.get(), 1);
		helper.fossilGrinding(ModItems.SHANTUNGOSAURUS_SKULL_FOSSIL.get(), ModItems.SHANTUNGOSAURUS_TISSUE.get(), 1);
		helper.fossilGrinding(ModItems.STEGOSAURUS_SKULL_FOSSIL.get(), ModItems.STEGOSAURUS_TISSUE.get(), 1);
		helper.fossilGrinding(ModItems.STYRACOSAURUS_SKULL_FOSSIL.get(), ModItems.STYRACOSAURUS_TISSUE.get(), 1);
		helper.fossilGrinding(ModItems.THERIZINOSAURUS_SKULL_FOSSIL.get(), ModItems.THERIZINOSAURUS_TISSUE.get(), 1);
		helper.fossilGrinding(ModItems.ALLOSAURUS_SKULL_FOSSIL.get(), ModItems.ALLOSAURUS_TISSUE.get(), 1);
		helper.fossilGrinding(ModItems.ALVAREZSAURUS_SKULL_FOSSIL.get(), ModItems.ALVAREZSAURUS_TISSUE.get(), 1);
		helper.fossilGrinding(ModItems.ANKYLOSAURUS_SKULL_FOSSIL.get(), ModItems.ANKYLOSAURUS_TISSUE.get(), 1);
		helper.fossilGrinding(ModItems.ARAMBOURGIANIA_SKULL_FOSSIL.get(), ModItems.ARAMBOURGIANIA_TISSUE.get(), 1);
		helper.fossilGrinding(ModItems.CARCHARODONTOSAURUS_SKULL_FOSSIL.get(), ModItems.CARCHARODONTOSAURUS_TISSUE.get(), 1);
		helper.fossilGrinding(ModItems.CEARADACTYLUS_SKULL_FOSSIL.get(), ModItems.CEARADACTYLUS_TISSUE.get(), 1);
		helper.fossilGrinding(ModItems.CHASMOSAURUS_SKULL_FOSSIL.get(), ModItems.CHASMOSAURUS_TISSUE.get(), 1);
		helper.fossilGrinding(ModItems.COELOPHYSIS_SKULL_FOSSIL.get(), ModItems.COELOPHYSIS_TISSUE.get(), 1);
		helper.fossilGrinding(ModItems.COELURUS_SKULL_FOSSIL.get(), ModItems.COELURUS_TISSUE.get(), 1);
		helper.fossilGrinding(ModItems.CORYTHOSAURUS_SKULL_FOSSIL.get(), ModItems.CORYTHOSAURUS_TISSUE.get(), 1);
		helper.fossilGrinding(ModItems.DIMORPHODON_SKULL_FOSSIL.get(), ModItems.DIMORPHODON_TISSUE.get(), 1);
		helper.fossilGrinding(ModItems.DRYOSAURUS_SKULL_FOSSIL.get(), ModItems.DRYOSAURUS_TISSUE.get(), 1);
		helper.fossilGrinding(ModItems.GEOSTERNBERGIA_SKULL_FOSSIL.get(), ModItems.GEOSTERNBERGIA_TISSUE.get(), 1);
		helper.fossilGrinding(ModItems.GUIDRACO_SKULL_FOSSIL.get(), ModItems.GUIDRACO_TISSUE.get(), 1);
		helper.fossilGrinding(ModItems.HADROSAURUS_SKULL_FOSSIL.get(), ModItems.HADROSAURUS_TISSUE.get(), 1);
		helper.fossilGrinding(ModItems.HYPSILOPHODON_SKULL_FOSSIL.get(), ModItems.HYPSILOPHODON_TISSUE.get(), 1);
		helper.fossilGrinding(ModItems.INOSTRANCEVIA_SKULL_FOSSIL.get(), ModItems.INOSTRANCEVIA_TISSUE.get(), 1);
		helper.fossilGrinding(ModItems.LAMBEOSAURUS_SKULL_FOSSIL.get(), ModItems.LAMBEOSAURUS_TISSUE.get(), 1);
		helper.fossilGrinding(ModItems.LUDODACTYLUS_SKULL_FOSSIL.get(), ModItems.LUDODACTYLUS_TISSUE.get(), 1);
		helper.fossilGrinding(ModItems.MAMENCHISAURUS_SKULL_FOSSIL.get(), ModItems.MAMENCHISAURUS_TISSUE.get(), 1);
		helper.fossilGrinding(ModItems.METRIACANTHOSAURUS_SKULL_FOSSIL.get(), ModItems.METRIACANTHOSAURUS_TISSUE.get(), 1);
		helper.fossilGrinding(ModItems.MOGANOPTERUS_SKULL_FOSSIL.get(), ModItems.MOGANOPTERUS_TISSUE.get(), 1);
		helper.fossilGrinding(ModItems.NYCTOSAURUS_SKULL_FOSSIL.get(), ModItems.NYCTOSAURUS_TISSUE.get(), 1);
		helper.fossilGrinding(ModItems.ORNITHOLESTES_SKULL_FOSSIL.get(), ModItems.ORNITHOLESTES_TISSUE.get(), 1);
		helper.fossilGrinding(ModItems.ORNITHOMIMUS_SKULL_FOSSIL.get(), ModItems.ORNITHOMIMUS_TISSUE.get(), 1);
		helper.fossilGrinding(ModItems.OVIRAPTOR_SKULL_FOSSIL.get(), ModItems.OVIRAPTOR_TISSUE.get(), 1);
		helper.fossilGrinding(ModItems.PACHYCEPHALOSAURUS_SKULL_FOSSIL.get(), ModItems.PACHYCEPHALOSAURUS_TISSUE.get(), 1);
		helper.fossilGrinding(ModItems.PROCERATOSAURUS_SKULL_FOSSIL.get(), ModItems.PROCERATOSAURUS_TISSUE.get(), 1);
		helper.fossilGrinding(ModItems.PTERANODON_SKULL_FOSSIL.get(), ModItems.PTERANODON_TISSUE.get(), 1);
		helper.fossilGrinding(ModItems.PTERODAUSTRO_SKULL_FOSSIL.get(), ModItems.PTERODAUSTRO_TISSUE.get(), 1);
		helper.fossilGrinding(ModItems.QUETZALCOATLUS_SKULL_FOSSIL.get(), ModItems.QUETZALCOATLUS_TISSUE.get(), 1);
		helper.fossilGrinding(ModItems.RAJASAURUS_SKULL_FOSSIL.get(), ModItems.RAJASAURUS_TISSUE.get(), 1);
		helper.fossilGrinding(ModItems.SEGISAURUS_SKULL_FOSSIL.get(), ModItems.SEGISAURUS_TISSUE.get(), 1);
		helper.fossilGrinding(ModItems.TAPEJARA_SKULL_FOSSIL.get(), ModItems.TAPEJARA_TISSUE.get(), 1);
		helper.fossilGrinding(ModItems.TITANOSAURUS_SKULL_FOSSIL.get(), ModItems.TITANOSAURUS_TISSUE.get(), 1);
		helper.fossilGrinding(ModItems.TROODON_SKULL_FOSSIL.get(), ModItems.TROODON_TISSUE.get(), 1);
		helper.fossilGrinding(ModItems.TROPEOGNATHUS_SKULL_FOSSIL.get(), ModItems.TROPEOGNATHUS_TISSUE.get(), 1);
		helper.fossilGrinding(ModItems.TUPUXUARA_SKULL_FOSSIL.get(), ModItems.TUPUXUARA_TISSUE.get(), 1);
		helper.fossilGrinding(ModItems.UTAHRAPTOR_SKULL_FOSSIL.get(), ModItems.UTAHRAPTOR_TISSUE.get(), 1);
		helper.fossilGrinding(ModItems.ZHENYUANOPTERUS_SKULL_FOSSIL.get(), ModItems.ZHENYUANOPTERUS_TISSUE.get(), 1);
		helper.fossilGrinding(ModItems.ACHILLOBATOR_SKULL_FOSSIL.get(), ModItems.ACHILLOBATOR_TISSUE.get(), 1);
		helper.fossilGrinding(ModItems.SUCHOMIMUS_SKULL_FOSSIL.get(), ModItems.SUCHOMIMUS_TISSUE.get(), 1);
		helper.fossilGrinding(ModItems.CHILESAURUS_SKULL_FOSSIL.get(), ModItems.CHILESAURUS_TISSUE.get(), 1);
		helper.fossilGrinding(ModItems.THESCELOSAURUS_SKULL_FOSSIL.get(), ModItems.THESCELOSAURUS_TISSUE.get(), 1);
		helper.fossilGrinding(ModItems.MUSSASAURUS_SKULL_FOSSIL.get(), ModItems.MUSSASAURUS_TISSUE.get(), 1);

		helper.skullToTissue(ModItems.FRESH_ALBERTOSAURUS_SKULL.get(), ModItems.ALBERTOSAURUS_TISSUE.get(), 1);
		helper.skullToTissue(ModItems.FRESH_APATOSAURUS_SKULL.get(), ModItems.APATOSAURUS_TISSUE.get(), 1);
		helper.skullToTissue(ModItems.FRESH_BRACHIOSAURUS_SKULL.get(), ModItems.BRACHIOSAURUS_TISSUE.get(), 1);
		helper.skullToTissue(ModItems.FRESH_CERATOSAURUS_SKULL.get(), ModItems.CERATOSAURUS_TISSUE.get(), 1);
		helper.skullToTissue(ModItems.FRESH_COMPSOGNATHUS_SKULL.get(), ModItems.COMPSOGNATHUS_TISSUE.get(), 1);
		helper.skullToTissue(ModItems.FRESH_DILOPHOSAURUS_SKULL.get(), ModItems.DILOPHOSAURUS_TISSUE.get(), 1);
		helper.skullToTissue(ModItems.FRESH_DIPLODOCUS_SKULL.get(), ModItems.DIPLODOCUS_TISSUE.get(), 1);
		helper.skullToTissue(ModItems.FRESH_GALLIMIMUS_SKULL.get(), ModItems.GALLIMIMUS_TISSUE.get(), 1);
		helper.skullToTissue(ModItems.FRESH_INDOMINUS_REX_SKULL.get(), ModItems.INDOMINUS_REX_TISSUE.get(), 1);
		helper.skullToTissue(ModItems.FRESH_OURANOSAURUS_SKULL.get(), ModItems.OURANOSAURUS_TISSUE.get(), 1);
		helper.skullToTissue(ModItems.FRESH_PARASAUROLOPHUS_SKULL.get(), ModItems.PARASAUROLOPHUS_TISSUE.get(), 1);
		helper.skullToTissue(ModItems.FRESH_SPINOSAURUS_SKULL.get(), ModItems.SPINOSAURUS_TISSUE.get(), 1);
		helper.skullToTissue(ModItems.FRESH_TRICERATOPS_SKULL.get(), ModItems.TRICERATOPS_TISSUE.get(), 1);
		helper.skullToTissue(ModItems.FRESH_TYRANNOSAURUS_REX_SKULL.get(), ModItems.TYRANNOSAURUS_REX_TISSUE.get(), 1);
		helper.skullToTissue(ModItems.FRESH_VELOCIRAPTOR_SKULL.get(), ModItems.VELOCIRAPTOR_TISSUE.get(), 1);
		helper.skullToTissue(ModItems.FRESH_BARYONYX_SKULL.get(), ModItems.BARYONYX_TISSUE.get(), 1);
		helper.skullToTissue(ModItems.FRESH_CARNOTAURUS_SKULL.get(), ModItems.CARNOTAURUS_TISSUE.get(), 1);
		helper.skullToTissue(ModItems.FRESH_CONCAVENATOR_SKULL.get(), ModItems.CONCAVENATOR_TISSUE.get(), 1);
		helper.skullToTissue(ModItems.FRESH_DEINONYCHUS_SKULL.get(), ModItems.DEINONYCHUS_TISSUE.get(), 1);
		helper.skullToTissue(ModItems.FRESH_EDMONTOSAURUS_SKULL.get(), ModItems.EDMONTOSAURUS_TISSUE.get(), 1);
		helper.skullToTissue(ModItems.FRESH_GIGANOTOSAURUS_SKULL.get(), ModItems.GIGANOTOSAURUS_TISSUE.get(), 1);
		helper.skullToTissue(ModItems.FRESH_GUANLONG_SKULL.get(), ModItems.GUANLONG_TISSUE.get(), 1);
		helper.skullToTissue(ModItems.FRESH_HERRERASAURUS_SKULL.get(), ModItems.HERRERASAURUS_TISSUE.get(), 1);
		helper.skullToTissue(ModItems.FRESH_MAJUNGASAURUS_SKULL.get(), ModItems.MAJUNGASAURUS_TISSUE.get(), 1);
		helper.skullToTissue(ModItems.FRESH_PROCOMPSOGNATHUS_SKULL.get(), ModItems.PROCOMPSOGNATHUS_TISSUE.get(), 1);
		helper.skullToTissue(ModItems.FRESH_PROTOCERATOPS_SKULL.get(), ModItems.PROTOCERATOPS_TISSUE.get(), 1);
		helper.skullToTissue(ModItems.FRESH_RUGOPS_SKULL.get(), ModItems.RUGOPS_TISSUE.get(), 1);
		helper.skullToTissue(ModItems.FRESH_SHANTUNGOSAURUS_SKULL.get(), ModItems.SHANTUNGOSAURUS_TISSUE.get(), 1);
		helper.skullToTissue(ModItems.FRESH_STEGOSAURUS_SKULL.get(), ModItems.STEGOSAURUS_TISSUE.get(), 1);
		helper.skullToTissue(ModItems.FRESH_STYRACOSAURUS_SKULL.get(), ModItems.STYRACOSAURUS_TISSUE.get(), 1);
		helper.skullToTissue(ModItems.FRESH_THERIZINOSAURUS_SKULL.get(), ModItems.THERIZINOSAURUS_TISSUE.get(), 1);
		helper.skullToTissue(ModItems.FRESH_DISTORTUS_REX_SKULL.get(), ModItems.DISTORTUS_REX_TISSUE.get(), 1);
		helper.skullToTissue(ModItems.FRESH_ALLOSAURUS_SKULL.get(), ModItems.ALLOSAURUS_TISSUE.get(), 1);
		helper.skullToTissue(ModItems.FRESH_ALVAREZSAURUS_SKULL.get(), ModItems.ALVAREZSAURUS_TISSUE.get(), 1);
		helper.skullToTissue(ModItems.FRESH_ANKYLOSAURUS_SKULL.get(), ModItems.ANKYLOSAURUS_TISSUE.get(), 1);
		helper.skullToTissue(ModItems.FRESH_ARAMBOURGIANIA_SKULL.get(), ModItems.ARAMBOURGIANIA_TISSUE.get(), 1);
		helper.skullToTissue(ModItems.FRESH_CARCHARODONTOSAURUS_SKULL.get(), ModItems.CARCHARODONTOSAURUS_TISSUE.get(), 1);
		helper.skullToTissue(ModItems.FRESH_CEARADACTYLUS_SKULL.get(), ModItems.CEARADACTYLUS_TISSUE.get(), 1);
		helper.skullToTissue(ModItems.FRESH_CHASMOSAURUS_SKULL.get(), ModItems.CHASMOSAURUS_TISSUE.get(), 1);
		helper.skullToTissue(ModItems.FRESH_COELOPHYSIS_SKULL.get(), ModItems.COELOPHYSIS_TISSUE.get(), 1);
		helper.skullToTissue(ModItems.FRESH_COELURUS_SKULL.get(), ModItems.COELURUS_TISSUE.get(), 1);
		helper.skullToTissue(ModItems.FRESH_CORYTHOSAURUS_SKULL.get(), ModItems.CORYTHOSAURUS_TISSUE.get(), 1);
		helper.skullToTissue(ModItems.FRESH_DIMORPHODON_SKULL.get(), ModItems.DIMORPHODON_TISSUE.get(), 1);
		helper.skullToTissue(ModItems.FRESH_DRYOSAURUS_SKULL.get(), ModItems.DRYOSAURUS_TISSUE.get(), 1);
		helper.skullToTissue(ModItems.FRESH_GEOSTERNBERGIA_SKULL.get(), ModItems.GEOSTERNBERGIA_TISSUE.get(), 1);
		helper.skullToTissue(ModItems.FRESH_GUIDRACO_SKULL.get(), ModItems.GUIDRACO_TISSUE.get(), 1);
		helper.skullToTissue(ModItems.FRESH_HADROSAURUS_SKULL.get(), ModItems.HADROSAURUS_TISSUE.get(), 1);
		helper.skullToTissue(ModItems.FRESH_HYPSILOPHODON_SKULL.get(), ModItems.HYPSILOPHODON_TISSUE.get(), 1);
		helper.skullToTissue(ModItems.FRESH_INDORAPTOR_SKULL.get(), ModItems.INDORAPTOR_TISSUE.get(), 1);
		helper.skullToTissue(ModItems.FRESH_INOSTRANCEVIA_SKULL.get(), ModItems.INOSTRANCEVIA_TISSUE.get(), 1);
		helper.skullToTissue(ModItems.FRESH_LAMBEOSAURUS_SKULL.get(), ModItems.LAMBEOSAURUS_TISSUE.get(), 1);
		helper.skullToTissue(ModItems.FRESH_LUDODACTYLUS_SKULL.get(), ModItems.LUDODACTYLUS_TISSUE.get(), 1);
		helper.skullToTissue(ModItems.FRESH_MAMENCHISAURUS_SKULL.get(), ModItems.MAMENCHISAURUS_TISSUE.get(), 1);
		helper.skullToTissue(ModItems.FRESH_METRIACANTHOSAURUS_SKULL.get(), ModItems.METRIACANTHOSAURUS_TISSUE.get(), 1);
		helper.skullToTissue(ModItems.FRESH_MOGANOPTERUS_SKULL.get(), ModItems.MOGANOPTERUS_TISSUE.get(), 1);
		helper.skullToTissue(ModItems.FRESH_NYCTOSAURUS_SKULL.get(), ModItems.NYCTOSAURUS_TISSUE.get(), 1);
		helper.skullToTissue(ModItems.FRESH_ORNITHOLESTES_SKULL.get(), ModItems.ORNITHOLESTES_TISSUE.get(), 1);
		helper.skullToTissue(ModItems.FRESH_ORNITHOMIMUS_SKULL.get(), ModItems.ORNITHOMIMUS_TISSUE.get(), 1);
		helper.skullToTissue(ModItems.FRESH_OVIRAPTOR_SKULL.get(), ModItems.OVIRAPTOR_TISSUE.get(), 1);
		helper.skullToTissue(ModItems.FRESH_PACHYCEPHALOSAURUS_SKULL.get(), ModItems.PACHYCEPHALOSAURUS_TISSUE.get(), 1);
		helper.skullToTissue(ModItems.FRESH_PROCERATOSAURUS_SKULL.get(), ModItems.PROCERATOSAURUS_TISSUE.get(), 1);
		helper.skullToTissue(ModItems.FRESH_PTERANODON_SKULL.get(), ModItems.PTERANODON_TISSUE.get(), 1);
		helper.skullToTissue(ModItems.FRESH_PTERODAUSTRO_SKULL.get(), ModItems.PTERODAUSTRO_TISSUE.get(), 1);
		helper.skullToTissue(ModItems.FRESH_QUETZALCOATLUS_SKULL.get(), ModItems.QUETZALCOATLUS_TISSUE.get(), 1);
		helper.skullToTissue(ModItems.FRESH_RAJASAURUS_SKULL.get(), ModItems.RAJASAURUS_TISSUE.get(), 1);
		helper.skullToTissue(ModItems.FRESH_SEGISAURUS_SKULL.get(), ModItems.SEGISAURUS_TISSUE.get(), 1);
		helper.skullToTissue(ModItems.FRESH_TAPEJARA_SKULL.get(), ModItems.TAPEJARA_TISSUE.get(), 1);
		helper.skullToTissue(ModItems.FRESH_TITANOSAURUS_SKULL.get(), ModItems.TITANOSAURUS_TISSUE.get(), 1);
		helper.skullToTissue(ModItems.FRESH_TROODON_SKULL.get(), ModItems.TROODON_TISSUE.get(), 1);
		helper.skullToTissue(ModItems.FRESH_TROPEOGNATHUS_SKULL.get(), ModItems.TROPEOGNATHUS_TISSUE.get(), 1);
		helper.skullToTissue(ModItems.FRESH_TUPUXUARA_SKULL.get(), ModItems.TUPUXUARA_TISSUE.get(), 1);
		helper.skullToTissue(ModItems.FRESH_UTAHRAPTOR_SKULL.get(), ModItems.UTAHRAPTOR_TISSUE.get(), 1);
		helper.skullToTissue(ModItems.FRESH_ZHENYUANOPTERUS_SKULL.get(), ModItems.ZHENYUANOPTERUS_TISSUE.get(), 1);
		helper.skullToTissue(ModItems.FRESH_ACHILLOBATOR_SKULL.get(), ModItems.ACHILLOBATOR_TISSUE.get(), 1);
		helper.skullToTissue(ModItems.FRESH_SUCHOMIMUS_SKULL.get(), ModItems.SUCHOMIMUS_TISSUE.get(), 1);
		helper.skullToTissue(ModItems.FRESH_CHILESAURUS_SKULL.get(), ModItems.CHILESAURUS_TISSUE.get(), 1);
		helper.skullToTissue(ModItems.FRESH_THESCELOSAURUS_SKULL.get(), ModItems.THESCELOSAURUS_TISSUE.get(), 1);
		helper.skullToTissue(ModItems.FRESH_MUSSASAURUS_SKULL.get(), ModItems.MUSSASAURUS_TISSUE.get(), 1);

		helper.dnaAnalyzing(ModItems.TEST_TUBE.get(), ModItems.FROG_MATERIAL.get(), ModItems.FROG_DNA.get(), 1);

		helper.dnaHybridizing(ModItems.INDOMINUS_REX_DNA.get(), 1,
			ModItems.TYRANNOSAURUS_REX_DNA.get(),
			ModItems.VELOCIRAPTOR_DNA.get(),
			ModItems.CARNOTAURUS_DNA.get(),
			ModItems.THERIZINOSAURUS_DNA.get(),
			ModItems.MAJUNGASAURUS_DNA.get(),
			ModItems.RUGOPS_DNA.get(),
			ModItems.GIGANOTOSAURUS_DNA.get());
		helper.dnaHybridizing(ModItems.DISTORTUS_REX_DNA.get(), 1,
			ModItems.TYRANNOSAURUS_REX_DNA.get(),
			ModItems.TITANOSAURUS_DNA.get(),
			ModItems.VELOCIRAPTOR_DNA.get());
		helper.dnaHybridizing(ModItems.INDORAPTOR_DNA.get(), 1,
			ModItems.INDOMINUS_REX_DNA.get(),
			ModItems.VELOCIRAPTOR_DNA.get());

        helper.embryonicMachine(ModItems.SYRINGE.get(), ModItems.APATOSAURUS_DNA.get(), ModItems.FROG_DNA.get(), ModItems.APATOSAURUS_SYRINGE.get(), 1);
        helper.embryonicMachine(ModItems.SYRINGE.get(), ModItems.ALBERTOSAURUS_DNA.get(), ModItems.FROG_DNA.get(), ModItems.ALBERTOSAURUS_SYRINGE.get(), 1);
        helper.embryonicMachine(ModItems.SYRINGE.get(), ModItems.BRACHIOSAURUS_DNA.get(), ModItems.FROG_DNA.get(), ModItems.BRACHIOSAURUS_SYRINGE.get(), 1);
        helper.embryonicMachine(ModItems.SYRINGE.get(), ModItems.CERATOSAURUS_DNA.get(), ModItems.FROG_DNA.get(), ModItems.CERATOSAURUS_SYRINGE.get(), 1);
        helper.embryonicMachine(ModItems.SYRINGE.get(), ModItems.COMPSOGNATHUS_DNA.get(), ModItems.FROG_DNA.get(), ModItems.COMPSOGNATHUS_SYRINGE.get(), 1);
        helper.embryonicMachine(ModItems.SYRINGE.get(), ModItems.DILOPHOSAURUS_DNA.get(), ModItems.FROG_DNA.get(), ModItems.DILOPHOSAURUS_SYRINGE.get(), 1);
        helper.embryonicMachine(ModItems.SYRINGE.get(), ModItems.DIPLODOCUS_DNA.get(), ModItems.FROG_DNA.get(), ModItems.DIPLODOCUS_SYRINGE.get(), 1);
        helper.embryonicMachine(ModItems.SYRINGE.get(), ModItems.GALLIMIMUS_DNA.get(), ModItems.FROG_DNA.get(), ModItems.GALLIMIMUS_SYRINGE.get(), 1);
        helper.embryonicMachine(ModItems.SYRINGE.get(), ModItems.INDOMINUS_REX_DNA.get(), ModItems.FROG_DNA.get(), ModItems.INDOMINUS_REX_SYRINGE.get(), 1);
        helper.embryonicMachine(ModItems.SYRINGE.get(), ModItems.OURANOSAURUS_DNA.get(), ModItems.FROG_DNA.get(), ModItems.OURANOSAURUS_SYRINGE.get(), 1);
        helper.embryonicMachine(ModItems.SYRINGE.get(), ModItems.PARASAUROLOPHUS_DNA.get(), ModItems.FROG_DNA.get(), ModItems.PARASAUROLOPHUS_SYRINGE.get(), 1);
        helper.embryonicMachine(ModItems.SYRINGE.get(), ModItems.SPINOSAURUS_DNA.get(), ModItems.FROG_DNA.get(), ModItems.SPINOSAURUS_SYRINGE.get(), 1);
        helper.embryonicMachine(ModItems.SYRINGE.get(), ModItems.TRICERATOPS_DNA.get(), ModItems.FROG_DNA.get(), ModItems.TRICERATOPS_SYRINGE.get(), 1);
        helper.embryonicMachine(ModItems.SYRINGE.get(), ModItems.TYRANNOSAURUS_REX_DNA.get(), ModItems.FROG_DNA.get(), ModItems.TYRANNOSAURUS_REX_SYRINGE.get(), 1);
        helper.embryonicMachine(ModItems.SYRINGE.get(), ModItems.VELOCIRAPTOR_DNA.get(), ModItems.FROG_DNA.get(), ModItems.VELOCIRAPTOR_SYRINGE.get(), 1);
        helper.embryonicMachine(ModItems.SYRINGE.get(), ModItems.BARYONYX_DNA.get(), ModItems.FROG_DNA.get(), ModItems.BARYONYX_SYRINGE.get(), 1);
        helper.embryonicMachine(ModItems.SYRINGE.get(), ModItems.CARNOTAURUS_DNA.get(), ModItems.FROG_DNA.get(), ModItems.CARNOTAURUS_SYRINGE.get(), 1);
        helper.embryonicMachine(ModItems.SYRINGE.get(), ModItems.CONCAVENATOR_DNA.get(), ModItems.FROG_DNA.get(), ModItems.CONCAVENATOR_SYRINGE.get(), 1);
        helper.embryonicMachine(ModItems.SYRINGE.get(), ModItems.DEINONYCHUS_DNA.get(), ModItems.FROG_DNA.get(), ModItems.DEINONYCHUS_SYRINGE.get(), 1);
        helper.embryonicMachine(ModItems.SYRINGE.get(), ModItems.EDMONTOSAURUS_DNA.get(), ModItems.FROG_DNA.get(), ModItems.EDMONTOSAURUS_SYRINGE.get(), 1);
        helper.embryonicMachine(ModItems.SYRINGE.get(), ModItems.GIGANOTOSAURUS_DNA.get(), ModItems.FROG_DNA.get(), ModItems.GIGANOTOSAURUS_SYRINGE.get(), 1);
        helper.embryonicMachine(ModItems.SYRINGE.get(), ModItems.GUANLONG_DNA.get(), ModItems.FROG_DNA.get(), ModItems.GUANLONG_SYRINGE.get(), 1);
        helper.embryonicMachine(ModItems.SYRINGE.get(), ModItems.HERRERASAURUS_DNA.get(), ModItems.FROG_DNA.get(), ModItems.HERRERASAURUS_SYRINGE.get(), 1);
        helper.embryonicMachine(ModItems.SYRINGE.get(), ModItems.MAJUNGASAURUS_DNA.get(), ModItems.FROG_DNA.get(), ModItems.MAJUNGASAURUS_SYRINGE.get(), 1);
        helper.embryonicMachine(ModItems.SYRINGE.get(), ModItems.PROCOMPSOGNATHUS_DNA.get(), ModItems.FROG_DNA.get(), ModItems.PROCOMPSOGNATHUS_SYRINGE.get(), 1);
        helper.embryonicMachine(ModItems.SYRINGE.get(), ModItems.PROTOCERATOPS_DNA.get(), ModItems.FROG_DNA.get(), ModItems.PROTOCERATOPS_SYRINGE.get(), 1);
        helper.embryonicMachine(ModItems.SYRINGE.get(), ModItems.RUGOPS_DNA.get(), ModItems.FROG_DNA.get(), ModItems.RUGOPS_SYRINGE.get(), 1);
        helper.embryonicMachine(ModItems.SYRINGE.get(), ModItems.SHANTUNGOSAURUS_DNA.get(), ModItems.FROG_DNA.get(), ModItems.SHANTUNGOSAURUS_SYRINGE.get(), 1);
        helper.embryonicMachine(ModItems.SYRINGE.get(), ModItems.STEGOSAURUS_DNA.get(), ModItems.FROG_DNA.get(), ModItems.STEGOSAURUS_SYRINGE.get(), 1);
        helper.embryonicMachine(ModItems.SYRINGE.get(), ModItems.STYRACOSAURUS_DNA.get(), ModItems.FROG_DNA.get(), ModItems.STYRACOSAURUS_SYRINGE.get(), 1);
        helper.embryonicMachine(ModItems.SYRINGE.get(), ModItems.THERIZINOSAURUS_DNA.get(), ModItems.FROG_DNA.get(), ModItems.THERIZINOSAURUS_SYRINGE.get(), 1);
        helper.embryonicMachine(ModItems.SYRINGE.get(), ModItems.DISTORTUS_REX_DNA.get(), ModItems.FROG_DNA.get(), ModItems.DISTORTUS_REX_SYRINGE.get(), 1);
        helper.embryonicMachine(ModItems.SYRINGE.get(), ModItems.ALLOSAURUS_DNA.get(), ModItems.FROG_DNA.get(), ModItems.ALLOSAURUS_SYRINGE.get(), 1);
        helper.embryonicMachine(ModItems.SYRINGE.get(), ModItems.ALVAREZSAURUS_DNA.get(), ModItems.FROG_DNA.get(), ModItems.ALVAREZSAURUS_SYRINGE.get(), 1);
        helper.embryonicMachine(ModItems.SYRINGE.get(), ModItems.ANKYLOSAURUS_DNA.get(), ModItems.FROG_DNA.get(), ModItems.ANKYLOSAURUS_SYRINGE.get(), 1);
        helper.embryonicMachine(ModItems.SYRINGE.get(), ModItems.ARAMBOURGIANIA_DNA.get(), ModItems.FROG_DNA.get(), ModItems.ARAMBOURGIANIA_SYRINGE.get(), 1);
        helper.embryonicMachine(ModItems.SYRINGE.get(), ModItems.CARCHARODONTOSAURUS_DNA.get(), ModItems.FROG_DNA.get(), ModItems.CARCHARODONTOSAURUS_SYRINGE.get(), 1);
        helper.embryonicMachine(ModItems.SYRINGE.get(), ModItems.CEARADACTYLUS_DNA.get(), ModItems.FROG_DNA.get(), ModItems.CEARADACTYLUS_SYRINGE.get(), 1);
        helper.embryonicMachine(ModItems.SYRINGE.get(), ModItems.CHASMOSAURUS_DNA.get(), ModItems.FROG_DNA.get(), ModItems.CHASMOSAURUS_SYRINGE.get(), 1);
        helper.embryonicMachine(ModItems.SYRINGE.get(), ModItems.COELOPHYSIS_DNA.get(), ModItems.FROG_DNA.get(), ModItems.COELOPHYSIS_SYRINGE.get(), 1);
        helper.embryonicMachine(ModItems.SYRINGE.get(), ModItems.COELURUS_DNA.get(), ModItems.FROG_DNA.get(), ModItems.COELURUS_SYRINGE.get(), 1);
        helper.embryonicMachine(ModItems.SYRINGE.get(), ModItems.CORYTHOSAURUS_DNA.get(), ModItems.FROG_DNA.get(), ModItems.CORYTHOSAURUS_SYRINGE.get(), 1);
        helper.embryonicMachine(ModItems.SYRINGE.get(), ModItems.DIMORPHODON_DNA.get(), ModItems.FROG_DNA.get(), ModItems.DIMORPHODON_SYRINGE.get(), 1);
        helper.embryonicMachine(ModItems.SYRINGE.get(), ModItems.DRYOSAURUS_DNA.get(), ModItems.FROG_DNA.get(), ModItems.DRYOSAURUS_SYRINGE.get(), 1);
        helper.embryonicMachine(ModItems.SYRINGE.get(), ModItems.GEOSTERNBERGIA_DNA.get(), ModItems.FROG_DNA.get(), ModItems.GEOSTERNBERGIA_SYRINGE.get(), 1);
        helper.embryonicMachine(ModItems.SYRINGE.get(), ModItems.GUIDRACO_DNA.get(), ModItems.FROG_DNA.get(), ModItems.GUIDRACO_SYRINGE.get(), 1);
        helper.embryonicMachine(ModItems.SYRINGE.get(), ModItems.HADROSAURUS_DNA.get(), ModItems.FROG_DNA.get(), ModItems.HADROSAURUS_SYRINGE.get(), 1);
        helper.embryonicMachine(ModItems.SYRINGE.get(), ModItems.HYPSILOPHODON_DNA.get(), ModItems.FROG_DNA.get(), ModItems.HYPSILOPHODON_SYRINGE.get(), 1);
        helper.embryonicMachine(ModItems.SYRINGE.get(), ModItems.INDORAPTOR_DNA.get(), ModItems.FROG_DNA.get(), ModItems.INDORAPTOR_SYRINGE.get(), 1);
        helper.embryonicMachine(ModItems.SYRINGE.get(), ModItems.INOSTRANCEVIA_DNA.get(), ModItems.FROG_DNA.get(), ModItems.INOSTRANCEVIA_SYRINGE.get(), 1);
        helper.embryonicMachine(ModItems.SYRINGE.get(), ModItems.LAMBEOSAURUS_DNA.get(), ModItems.FROG_DNA.get(), ModItems.LAMBEOSAURUS_SYRINGE.get(), 1);
        helper.embryonicMachine(ModItems.SYRINGE.get(), ModItems.LUDODACTYLUS_DNA.get(), ModItems.FROG_DNA.get(), ModItems.LUDODACTYLUS_SYRINGE.get(), 1);
        helper.embryonicMachine(ModItems.SYRINGE.get(), ModItems.MAMENCHISAURUS_DNA.get(), ModItems.FROG_DNA.get(), ModItems.MAMENCHISAURUS_SYRINGE.get(), 1);
        helper.embryonicMachine(ModItems.SYRINGE.get(), ModItems.METRIACANTHOSAURUS_DNA.get(), ModItems.FROG_DNA.get(), ModItems.METRIACANTHOSAURUS_SYRINGE.get(), 1);
        helper.embryonicMachine(ModItems.SYRINGE.get(), ModItems.MOGANOPTERUS_DNA.get(), ModItems.FROG_DNA.get(), ModItems.MOGANOPTERUS_SYRINGE.get(), 1);
        helper.embryonicMachine(ModItems.SYRINGE.get(), ModItems.NYCTOSAURUS_DNA.get(), ModItems.FROG_DNA.get(), ModItems.NYCTOSAURUS_SYRINGE.get(), 1);
        helper.embryonicMachine(ModItems.SYRINGE.get(), ModItems.ORNITHOLESTES_DNA.get(), ModItems.FROG_DNA.get(), ModItems.ORNITHOLESTES_SYRINGE.get(), 1);
        helper.embryonicMachine(ModItems.SYRINGE.get(), ModItems.ORNITHOMIMUS_DNA.get(), ModItems.FROG_DNA.get(), ModItems.ORNITHOMIMUS_SYRINGE.get(), 1);
        helper.embryonicMachine(ModItems.SYRINGE.get(), ModItems.OVIRAPTOR_DNA.get(), ModItems.FROG_DNA.get(), ModItems.OVIRAPTOR_SYRINGE.get(), 1);
        helper.embryonicMachine(ModItems.SYRINGE.get(), ModItems.PACHYCEPHALOSAURUS_DNA.get(), ModItems.FROG_DNA.get(), ModItems.PACHYCEPHALOSAURUS_SYRINGE.get(), 1);
        helper.embryonicMachine(ModItems.SYRINGE.get(), ModItems.PROCERATOSAURUS_DNA.get(), ModItems.FROG_DNA.get(), ModItems.PROCERATOSAURUS_SYRINGE.get(), 1);
        helper.embryonicMachine(ModItems.SYRINGE.get(), ModItems.PTERANODON_DNA.get(), ModItems.FROG_DNA.get(), ModItems.PTERANODON_SYRINGE.get(), 1);
        helper.embryonicMachine(ModItems.SYRINGE.get(), ModItems.PTERODAUSTRO_DNA.get(), ModItems.FROG_DNA.get(), ModItems.PTERODAUSTRO_SYRINGE.get(), 1);
        helper.embryonicMachine(ModItems.SYRINGE.get(), ModItems.QUETZALCOATLUS_DNA.get(), ModItems.FROG_DNA.get(), ModItems.QUETZALCOATLUS_SYRINGE.get(), 1);
        helper.embryonicMachine(ModItems.SYRINGE.get(), ModItems.RAJASAURUS_DNA.get(), ModItems.FROG_DNA.get(), ModItems.RAJASAURUS_SYRINGE.get(), 1);
        helper.embryonicMachine(ModItems.SYRINGE.get(), ModItems.SEGISAURUS_DNA.get(), ModItems.FROG_DNA.get(), ModItems.SEGISAURUS_SYRINGE.get(), 1);
        helper.embryonicMachine(ModItems.SYRINGE.get(), ModItems.TAPEJARA_DNA.get(), ModItems.FROG_DNA.get(), ModItems.TAPEJARA_SYRINGE.get(), 1);
        helper.embryonicMachine(ModItems.SYRINGE.get(), ModItems.TITANOSAURUS_DNA.get(), ModItems.FROG_DNA.get(), ModItems.TITANOSAURUS_SYRINGE.get(), 1);
        helper.embryonicMachine(ModItems.SYRINGE.get(), ModItems.TROODON_DNA.get(), ModItems.FROG_DNA.get(), ModItems.TROODON_SYRINGE.get(), 1);
        helper.embryonicMachine(ModItems.SYRINGE.get(), ModItems.TROPEOGNATHUS_DNA.get(), ModItems.FROG_DNA.get(), ModItems.TROPEOGNATHUS_SYRINGE.get(), 1);
        helper.embryonicMachine(ModItems.SYRINGE.get(), ModItems.TUPUXUARA_DNA.get(), ModItems.FROG_DNA.get(), ModItems.TUPUXUARA_SYRINGE.get(), 1);
        helper.embryonicMachine(ModItems.SYRINGE.get(), ModItems.UTAHRAPTOR_DNA.get(), ModItems.FROG_DNA.get(), ModItems.UTAHRAPTOR_SYRINGE.get(), 1);
        helper.embryonicMachine(ModItems.SYRINGE.get(), ModItems.ZHENYUANOPTERUS_DNA.get(), ModItems.FROG_DNA.get(), ModItems.ZHENYUANOPTERUS_SYRINGE.get(), 1);
        helper.embryonicMachine(ModItems.SYRINGE.get(), ModItems.ACHILLOBATOR_DNA.get(), ModItems.FROG_DNA.get(), ModItems.ACHILLOBATOR_SYRINGE.get(), 1);
        helper.embryonicMachine(ModItems.SYRINGE.get(), ModItems.SUCHOMIMUS_DNA.get(), ModItems.FROG_DNA.get(), ModItems.SUCHOMIMUS_SYRINGE.get(), 1);
        helper.embryonicMachine(ModItems.SYRINGE.get(), ModItems.CHILESAURUS_DNA.get(), ModItems.FROG_DNA.get(), ModItems.CHILESAURUS_SYRINGE.get(), 1);
        helper.embryonicMachine(ModItems.SYRINGE.get(), ModItems.THESCELOSAURUS_DNA.get(), ModItems.FROG_DNA.get(), ModItems.THESCELOSAURUS_SYRINGE.get(), 1);
        helper.embryonicMachine(ModItems.SYRINGE.get(), ModItems.MUSSASAURUS_DNA.get(), ModItems.FROG_DNA.get(), ModItems.MUSSASAURUS_SYRINGE.get(), 1);

		helper.embryoCalcification(ModItems.ALBERTOSAURUS_SYRINGE.get(), Items.EGG, ModBlocks.ALBERTOSAURUS_EGG.get(), 1);
		helper.embryoCalcification(ModItems.APATOSAURUS_SYRINGE.get(), Items.EGG, ModBlocks.APATOSAURUS_EGG.get(), 1);
		helper.embryoCalcification(ModItems.BRACHIOSAURUS_SYRINGE.get(), Items.EGG, ModBlocks.BRACHIOSAURUS_EGG.get(), 1);
		helper.embryoCalcification(ModItems.CERATOSAURUS_SYRINGE.get(), Items.EGG, ModBlocks.CERATOSAURUS_EGG.get(), 1);
		helper.embryoCalcification(ModItems.COMPSOGNATHUS_SYRINGE.get(), Items.EGG, ModBlocks.COMPSOGNATHUS_EGG.get(), 1);
		helper.embryoCalcification(ModItems.DILOPHOSAURUS_SYRINGE.get(), Items.EGG, ModBlocks.DILOPHOSAURUS_EGG.get(), 1);
		helper.embryoCalcification(ModItems.DIPLODOCUS_SYRINGE.get(), Items.EGG, ModBlocks.DIPLODOCUS_EGG.get(), 1);
		helper.embryoCalcification(ModItems.GALLIMIMUS_SYRINGE.get(), Items.EGG, ModBlocks.GALLIMIMUS_EGG.get(), 1);
		helper.embryoCalcification(ModItems.INDOMINUS_REX_SYRINGE.get(), Items.EGG, ModBlocks.INDOMINUS_REX_EGG.get(), 1);
		helper.embryoCalcification(ModItems.OURANOSAURUS_SYRINGE.get(), Items.EGG, ModBlocks.OURANOSAURUS_EGG.get(), 1);
		helper.embryoCalcification(ModItems.PARASAUROLOPHUS_SYRINGE.get(), Items.EGG, ModBlocks.PARASAUROLOPHUS_EGG.get(), 1);
		helper.embryoCalcification(ModItems.SPINOSAURUS_SYRINGE.get(), Items.EGG, ModBlocks.SPINOSAURUS_EGG.get(), 1);
		helper.embryoCalcification(ModItems.TRICERATOPS_SYRINGE.get(), Items.EGG, ModBlocks.TRICERATOPS_EGG.get(), 1);
		helper.embryoCalcification(ModItems.TYRANNOSAURUS_REX_SYRINGE.get(), Items.EGG, ModBlocks.TYRANNOSAURUS_REX_EGG.get(), 1);
		helper.embryoCalcification(ModItems.VELOCIRAPTOR_SYRINGE.get(), Items.EGG, ModBlocks.VELOCIRAPTOR_EGG.get(), 1);
		helper.embryoCalcification(ModItems.BARYONYX_SYRINGE.get(), Items.EGG, ModBlocks.BARYONYX_EGG.get(), 1);
		helper.embryoCalcification(ModItems.CARNOTAURUS_SYRINGE.get(), Items.EGG, ModBlocks.CARNOTAURUS_EGG.get(), 1);
		helper.embryoCalcification(ModItems.CONCAVENATOR_SYRINGE.get(), Items.EGG, ModBlocks.CONCAVENATOR_EGG.get(), 1);
		helper.embryoCalcification(ModItems.DEINONYCHUS_SYRINGE.get(), Items.EGG, ModBlocks.DEINONYCHUS_EGG.get(), 1);
		helper.embryoCalcification(ModItems.EDMONTOSAURUS_SYRINGE.get(), Items.EGG, ModBlocks.EDMONTOSAURUS_EGG.get(), 1);
		helper.embryoCalcification(ModItems.GIGANOTOSAURUS_SYRINGE.get(), Items.EGG, ModBlocks.GIGANOTOSAURUS_EGG.get(), 1);
		helper.embryoCalcification(ModItems.GUANLONG_SYRINGE.get(), Items.EGG, ModBlocks.GUANLONG_EGG.get(), 1);
		helper.embryoCalcification(ModItems.HERRERASAURUS_SYRINGE.get(), Items.EGG, ModBlocks.HERRERASAURUS_EGG.get(), 1);
		helper.embryoCalcification(ModItems.MAJUNGASAURUS_SYRINGE.get(), Items.EGG, ModBlocks.MAJUNGASAURUS_EGG.get(), 1);
		helper.embryoCalcification(ModItems.PROCOMPSOGNATHUS_SYRINGE.get(), Items.EGG, ModBlocks.PROCOMPSOGNATHUS_EGG.get(), 1);
		helper.embryoCalcification(ModItems.PROTOCERATOPS_SYRINGE.get(), Items.EGG, ModBlocks.PROTOCERATOPS_EGG.get(), 1);
		helper.embryoCalcification(ModItems.RUGOPS_SYRINGE.get(), Items.EGG, ModBlocks.RUGOPS_EGG.get(), 1);
		helper.embryoCalcification(ModItems.SHANTUNGOSAURUS_SYRINGE.get(), Items.EGG, ModBlocks.SHANTUNGOSAURUS_EGG.get(), 1);
		helper.embryoCalcification(ModItems.STEGOSAURUS_SYRINGE.get(), Items.EGG, ModBlocks.STEGOSAURUS_EGG.get(), 1);
		helper.embryoCalcification(ModItems.STYRACOSAURUS_SYRINGE.get(), Items.EGG, ModBlocks.STYRACOSAURUS_EGG.get(), 1);
		helper.embryoCalcification(ModItems.THERIZINOSAURUS_SYRINGE.get(), Items.EGG, ModBlocks.THERIZINOSAURUS_EGG.get(), 1);
		helper.embryoCalcification(ModItems.DISTORTUS_REX_SYRINGE.get(), Items.EGG, ModBlocks.DISTORTUS_REX_EGG.get(), 1);
		helper.embryoCalcification(ModItems.ALLOSAURUS_SYRINGE.get(), Items.EGG, ModBlocks.ALLOSAURUS_EGG.get(), 1);
		helper.embryoCalcification(ModItems.ALVAREZSAURUS_SYRINGE.get(), Items.EGG, ModBlocks.ALVAREZSAURUS_EGG.get(), 1);
		helper.embryoCalcification(ModItems.ANKYLOSAURUS_SYRINGE.get(), Items.EGG, ModBlocks.ANKYLOSAURUS_EGG.get(), 1);
		helper.embryoCalcification(ModItems.ARAMBOURGIANIA_SYRINGE.get(), Items.EGG, ModBlocks.ARAMBOURGIANIA_EGG.get(), 1);
		helper.embryoCalcification(ModItems.CARCHARODONTOSAURUS_SYRINGE.get(), Items.EGG, ModBlocks.CARCHARODONTOSAURUS_EGG.get(), 1);
		helper.embryoCalcification(ModItems.CEARADACTYLUS_SYRINGE.get(), Items.EGG, ModBlocks.CEARADACTYLUS_EGG.get(), 1);
		helper.embryoCalcification(ModItems.CHASMOSAURUS_SYRINGE.get(), Items.EGG, ModBlocks.CHASMOSAURUS_EGG.get(), 1);
		helper.embryoCalcification(ModItems.COELOPHYSIS_SYRINGE.get(), Items.EGG, ModBlocks.COELOPHYSIS_EGG.get(), 1);
		helper.embryoCalcification(ModItems.COELURUS_SYRINGE.get(), Items.EGG, ModBlocks.COELURUS_EGG.get(), 1);
		helper.embryoCalcification(ModItems.CORYTHOSAURUS_SYRINGE.get(), Items.EGG, ModBlocks.CORYTHOSAURUS_EGG.get(), 1);
		helper.embryoCalcification(ModItems.DIMORPHODON_SYRINGE.get(), Items.EGG, ModBlocks.DIMORPHODON_EGG.get(), 1);
		helper.embryoCalcification(ModItems.DRYOSAURUS_SYRINGE.get(), Items.EGG, ModBlocks.DRYOSAURUS_EGG.get(), 1);
		helper.embryoCalcification(ModItems.GEOSTERNBERGIA_SYRINGE.get(), Items.EGG, ModBlocks.GEOSTERNBERGIA_EGG.get(), 1);
		helper.embryoCalcification(ModItems.GUIDRACO_SYRINGE.get(), Items.EGG, ModBlocks.GUIDRACO_EGG.get(), 1);
		helper.embryoCalcification(ModItems.HADROSAURUS_SYRINGE.get(), Items.EGG, ModBlocks.HADROSAURUS_EGG.get(), 1);
		helper.embryoCalcification(ModItems.HYPSILOPHODON_SYRINGE.get(), Items.EGG, ModBlocks.HYPSILOPHODON_EGG.get(), 1);
		helper.embryoCalcification(ModItems.INDORAPTOR_SYRINGE.get(), Items.EGG, ModBlocks.INDORAPTOR_EGG.get(), 1);
		helper.embryoCalcification(ModItems.INOSTRANCEVIA_SYRINGE.get(), Items.EGG, ModBlocks.INOSTRANCEVIA_EGG.get(), 1);
		helper.embryoCalcification(ModItems.LAMBEOSAURUS_SYRINGE.get(), Items.EGG, ModBlocks.LAMBEOSAURUS_EGG.get(), 1);
		helper.embryoCalcification(ModItems.LUDODACTYLUS_SYRINGE.get(), Items.EGG, ModBlocks.LUDODACTYLUS_EGG.get(), 1);
		helper.embryoCalcification(ModItems.MAMENCHISAURUS_SYRINGE.get(), Items.EGG, ModBlocks.MAMENCHISAURUS_EGG.get(), 1);
		helper.embryoCalcification(ModItems.METRIACANTHOSAURUS_SYRINGE.get(), Items.EGG, ModBlocks.METRIACANTHOSAURUS_EGG.get(), 1);
		helper.embryoCalcification(ModItems.MOGANOPTERUS_SYRINGE.get(), Items.EGG, ModBlocks.MOGANOPTERUS_EGG.get(), 1);
		helper.embryoCalcification(ModItems.NYCTOSAURUS_SYRINGE.get(), Items.EGG, ModBlocks.NYCTOSAURUS_EGG.get(), 1);
		helper.embryoCalcification(ModItems.ORNITHOLESTES_SYRINGE.get(), Items.EGG, ModBlocks.ORNITHOLESTES_EGG.get(), 1);
		helper.embryoCalcification(ModItems.ORNITHOMIMUS_SYRINGE.get(), Items.EGG, ModBlocks.ORNITHOMIMUS_EGG.get(), 1);
		helper.embryoCalcification(ModItems.OVIRAPTOR_SYRINGE.get(), Items.EGG, ModBlocks.OVIRAPTOR_EGG.get(), 1);
		helper.embryoCalcification(ModItems.PACHYCEPHALOSAURUS_SYRINGE.get(), Items.EGG, ModBlocks.PACHYCEPHALOSAURUS_EGG.get(), 1);
		helper.embryoCalcification(ModItems.PROCERATOSAURUS_SYRINGE.get(), Items.EGG, ModBlocks.PROCERATOSAURUS_EGG.get(), 1);
		helper.embryoCalcification(ModItems.PTERANODON_SYRINGE.get(), Items.EGG, ModBlocks.PTERANODON_EGG.get(), 1);
		helper.embryoCalcification(ModItems.PTERODAUSTRO_SYRINGE.get(), Items.EGG, ModBlocks.PTERODAUSTRO_EGG.get(), 1);
		helper.embryoCalcification(ModItems.QUETZALCOATLUS_SYRINGE.get(), Items.EGG, ModBlocks.QUETZALCOATLUS_EGG.get(), 1);
		helper.embryoCalcification(ModItems.RAJASAURUS_SYRINGE.get(), Items.EGG, ModBlocks.RAJASAURUS_EGG.get(), 1);
		helper.embryoCalcification(ModItems.SEGISAURUS_SYRINGE.get(), Items.EGG, ModBlocks.SEGISAURUS_EGG.get(), 1);
		helper.embryoCalcification(ModItems.TAPEJARA_SYRINGE.get(), Items.EGG, ModBlocks.TAPEJARA_EGG.get(), 1);
		helper.embryoCalcification(ModItems.TITANOSAURUS_SYRINGE.get(), Items.EGG, ModBlocks.TITANOSAURUS_EGG.get(), 1);
		helper.embryoCalcification(ModItems.TROODON_SYRINGE.get(), Items.EGG, ModBlocks.TROODON_EGG.get(), 1);
		helper.embryoCalcification(ModItems.TROPEOGNATHUS_SYRINGE.get(), Items.EGG, ModBlocks.TROPEOGNATHUS_EGG.get(), 1);
		helper.embryoCalcification(ModItems.TUPUXUARA_SYRINGE.get(), Items.EGG, ModBlocks.TUPUXUARA_EGG.get(), 1);
		helper.embryoCalcification(ModItems.UTAHRAPTOR_SYRINGE.get(), Items.EGG, ModBlocks.UTAHRAPTOR_EGG.get(), 1);
		helper.embryoCalcification(ModItems.ZHENYUANOPTERUS_SYRINGE.get(), Items.EGG, ModBlocks.ZHENYUANOPTERUS_EGG.get(), 1);
		helper.embryoCalcification(ModItems.ACHILLOBATOR_SYRINGE.get(), Items.EGG, ModBlocks.ACHILLOBATOR_EGG.get(), 1);
		helper.embryoCalcification(ModItems.SUCHOMIMUS_SYRINGE.get(), Items.EGG, ModBlocks.SUCHOMIMUS_EGG.get(), 1);
		helper.embryoCalcification(ModItems.CHILESAURUS_SYRINGE.get(), Items.EGG, ModBlocks.CHILESAURUS_EGG.get(), 1);
		helper.embryoCalcification(ModItems.THESCELOSAURUS_SYRINGE.get(), Items.EGG, ModBlocks.THESCELOSAURUS_EGG.get(), 1);
		helper.embryoCalcification(ModItems.MUSSASAURUS_SYRINGE.get(), Items.EGG, ModBlocks.MUSSASAURUS_EGG.get(), 1);

		helper.incubating(ModBlocks.APATOSAURUS_EGG.get(), ModBlocks.INCUBATED_APATOSAURUS_EGG.get(), 1);
		helper.incubating(ModBlocks.ALBERTOSAURUS_EGG.get(), ModBlocks.INCUBATED_ALBERTOSAURUS_EGG.get(), 1);
		helper.incubating(ModBlocks.BRACHIOSAURUS_EGG.get(), ModBlocks.INCUBATED_BRACHIOSAURUS_EGG.get(), 1);
		helper.incubating(ModBlocks.CERATOSAURUS_EGG.get(), ModBlocks.INCUBATED_CERATOSAURUS_EGG.get(), 1);
		helper.incubating(ModBlocks.COMPSOGNATHUS_EGG.get(), ModBlocks.INCUBATED_COMPSOGNATHUS_EGG.get(), 1);
		helper.incubating(ModBlocks.DILOPHOSAURUS_EGG.get(), ModBlocks.INCUBATED_DILOPHOSAURUS_EGG.get(), 1);
		helper.incubating(ModBlocks.DIPLODOCUS_EGG.get(), ModBlocks.INCUBATED_DIPLODOCUS_EGG.get(), 1);
		helper.incubating(ModBlocks.PARASAUROLOPHUS_EGG.get(), ModBlocks.INCUBATED_PARASAUROLOPHUS_EGG.get(), 1);
		helper.incubating(ModBlocks.SPINOSAURUS_EGG.get(), ModBlocks.INCUBATED_SPINOSAURUS_EGG.get(), 1);
		helper.incubating(ModBlocks.OURANOSAURUS_EGG.get(), ModBlocks.INCUBATED_OURANOSAURUS_EGG.get(), 1);
		helper.incubating(ModBlocks.GALLIMIMUS_EGG.get(), ModBlocks.INCUBATED_GALLIMIMUS_EGG.get(), 1);
		helper.incubating(ModBlocks.INDOMINUS_REX_EGG.get(), ModBlocks.INCUBATED_INDOMINUS_REX_EGG.get(), 1);
		helper.incubating(ModBlocks.VELOCIRAPTOR_EGG.get(), ModBlocks.INCUBATED_VELOCIRAPTOR_EGG.get(), 1);
		helper.incubating(ModBlocks.TYRANNOSAURUS_REX_EGG.get(), ModBlocks.INCUBATED_TYRANNOSAURUS_REX_EGG.get(), 1);
		helper.incubating(ModBlocks.TRICERATOPS_EGG.get(), ModBlocks.INCUBATED_TRICERATOPS_EGG.get(), 1);
		helper.incubating(ModBlocks.BARYONYX_EGG.get(), ModBlocks.INCUBATED_BARYONYX_EGG.get(), 1);
		helper.incubating(ModBlocks.CARNOTAURUS_EGG.get(), ModBlocks.INCUBATED_CARNOTAURUS_EGG.get(), 1);
		helper.incubating(ModBlocks.CONCAVENATOR_EGG.get(), ModBlocks.INCUBATED_CONCAVENATOR_EGG.get(), 1);
		helper.incubating(ModBlocks.DEINONYCHUS_EGG.get(), ModBlocks.INCUBATED_DEINONYCHUS_EGG.get(), 1);
		helper.incubating(ModBlocks.EDMONTOSAURUS_EGG.get(), ModBlocks.INCUBATED_EDMONTOSAURUS_EGG.get(), 1);
		helper.incubating(ModBlocks.GIGANOTOSAURUS_EGG.get(), ModBlocks.INCUBATED_GIGANOTOSAURUS_EGG.get(), 1);
		helper.incubating(ModBlocks.GUANLONG_EGG.get(), ModBlocks.INCUBATED_GUANLONG_EGG.get(), 1);
		helper.incubating(ModBlocks.HERRERASAURUS_EGG.get(), ModBlocks.INCUBATED_HERRERASAURUS_EGG.get(), 1);
		helper.incubating(ModBlocks.MAJUNGASAURUS_EGG.get(), ModBlocks.INCUBATED_MAJUNGASAURUS_EGG.get(), 1);
		helper.incubating(ModBlocks.PROCOMPSOGNATHUS_EGG.get(), ModBlocks.INCUBATED_PROCOMPSOGNATHUS_EGG.get(), 1);
		helper.incubating(ModBlocks.PROTOCERATOPS_EGG.get(), ModBlocks.INCUBATED_PROTOCERATOPS_EGG.get(), 1);
		helper.incubating(ModBlocks.RUGOPS_EGG.get(), ModBlocks.INCUBATED_RUGOPS_EGG.get(), 1);
		helper.incubating(ModBlocks.SHANTUNGOSAURUS_EGG.get(), ModBlocks.INCUBATED_SHANTUNGOSAURUS_EGG.get(), 1);
		helper.incubating(ModBlocks.STEGOSAURUS_EGG.get(), ModBlocks.INCUBATED_STEGOSAURUS_EGG.get(), 1);
		helper.incubating(ModBlocks.STYRACOSAURUS_EGG.get(), ModBlocks.INCUBATED_STYRACOSAURUS_EGG.get(), 1);
		helper.incubating(ModBlocks.THERIZINOSAURUS_EGG.get(), ModBlocks.INCUBATED_THERIZINOSAURUS_EGG.get(), 1);
		helper.incubating(ModBlocks.DISTORTUS_REX_EGG.get(), ModBlocks.INCUBATED_DISTORTUS_REX_EGG.get(), 1);
		helper.incubating(ModBlocks.ALLOSAURUS_EGG.get(), ModBlocks.INCUBATED_ALLOSAURUS_EGG.get(), 1);
		helper.incubating(ModBlocks.ALVAREZSAURUS_EGG.get(), ModBlocks.INCUBATED_ALVAREZSAURUS_EGG.get(), 1);
		helper.incubating(ModBlocks.ANKYLOSAURUS_EGG.get(), ModBlocks.INCUBATED_ANKYLOSAURUS_EGG.get(), 1);
		helper.incubating(ModBlocks.ARAMBOURGIANIA_EGG.get(), ModBlocks.INCUBATED_ARAMBOURGIANIA_EGG.get(), 1);
		helper.incubating(ModBlocks.CARCHARODONTOSAURUS_EGG.get(), ModBlocks.INCUBATED_CARCHARODONTOSAURUS_EGG.get(), 1);
		helper.incubating(ModBlocks.CEARADACTYLUS_EGG.get(), ModBlocks.INCUBATED_CEARADACTYLUS_EGG.get(), 1);
		helper.incubating(ModBlocks.CHASMOSAURUS_EGG.get(), ModBlocks.INCUBATED_CHASMOSAURUS_EGG.get(), 1);
		helper.incubating(ModBlocks.COELOPHYSIS_EGG.get(), ModBlocks.INCUBATED_COELOPHYSIS_EGG.get(), 1);
		helper.incubating(ModBlocks.COELURUS_EGG.get(), ModBlocks.INCUBATED_COELURUS_EGG.get(), 1);
		helper.incubating(ModBlocks.CORYTHOSAURUS_EGG.get(), ModBlocks.INCUBATED_CORYTHOSAURUS_EGG.get(), 1);
		helper.incubating(ModBlocks.DIMORPHODON_EGG.get(), ModBlocks.INCUBATED_DIMORPHODON_EGG.get(), 1);
		helper.incubating(ModBlocks.DRYOSAURUS_EGG.get(), ModBlocks.INCUBATED_DRYOSAURUS_EGG.get(), 1);
		helper.incubating(ModBlocks.GEOSTERNBERGIA_EGG.get(), ModBlocks.INCUBATED_GEOSTERNBERGIA_EGG.get(), 1);
		helper.incubating(ModBlocks.GUIDRACO_EGG.get(), ModBlocks.INCUBATED_GUIDRACO_EGG.get(), 1);
		helper.incubating(ModBlocks.HADROSAURUS_EGG.get(), ModBlocks.INCUBATED_HADROSAURUS_EGG.get(), 1);
		helper.incubating(ModBlocks.HYPSILOPHODON_EGG.get(), ModBlocks.INCUBATED_HYPSILOPHODON_EGG.get(), 1);
		helper.incubating(ModBlocks.INDORAPTOR_EGG.get(), ModBlocks.INCUBATED_INDORAPTOR_EGG.get(), 1);
		helper.incubating(ModBlocks.INOSTRANCEVIA_EGG.get(), ModBlocks.INCUBATED_INOSTRANCEVIA_EGG.get(), 1);
		helper.incubating(ModBlocks.LAMBEOSAURUS_EGG.get(), ModBlocks.INCUBATED_LAMBEOSAURUS_EGG.get(), 1);
		helper.incubating(ModBlocks.LUDODACTYLUS_EGG.get(), ModBlocks.INCUBATED_LUDODACTYLUS_EGG.get(), 1);
		helper.incubating(ModBlocks.MAMENCHISAURUS_EGG.get(), ModBlocks.INCUBATED_MAMENCHISAURUS_EGG.get(), 1);
		helper.incubating(ModBlocks.METRIACANTHOSAURUS_EGG.get(), ModBlocks.INCUBATED_METRIACANTHOSAURUS_EGG.get(), 1);
		helper.incubating(ModBlocks.MOGANOPTERUS_EGG.get(), ModBlocks.INCUBATED_MOGANOPTERUS_EGG.get(), 1);
		helper.incubating(ModBlocks.NYCTOSAURUS_EGG.get(), ModBlocks.INCUBATED_NYCTOSAURUS_EGG.get(), 1);
		helper.incubating(ModBlocks.ORNITHOLESTES_EGG.get(), ModBlocks.INCUBATED_ORNITHOLESTES_EGG.get(), 1);
		helper.incubating(ModBlocks.ORNITHOMIMUS_EGG.get(), ModBlocks.INCUBATED_ORNITHOMIMUS_EGG.get(), 1);
		helper.incubating(ModBlocks.OVIRAPTOR_EGG.get(), ModBlocks.INCUBATED_OVIRAPTOR_EGG.get(), 1);
		helper.incubating(ModBlocks.PACHYCEPHALOSAURUS_EGG.get(), ModBlocks.INCUBATED_PACHYCEPHALOSAURUS_EGG.get(), 1);
		helper.incubating(ModBlocks.PROCERATOSAURUS_EGG.get(), ModBlocks.INCUBATED_PROCERATOSAURUS_EGG.get(), 1);
		helper.incubating(ModBlocks.PTERANODON_EGG.get(), ModBlocks.INCUBATED_PTERANODON_EGG.get(), 1);
		helper.incubating(ModBlocks.PTERODAUSTRO_EGG.get(), ModBlocks.INCUBATED_PTERODAUSTRO_EGG.get(), 1);
		helper.incubating(ModBlocks.QUETZALCOATLUS_EGG.get(), ModBlocks.INCUBATED_QUETZALCOATLUS_EGG.get(), 1);
		helper.incubating(ModBlocks.RAJASAURUS_EGG.get(), ModBlocks.INCUBATED_RAJASAURUS_EGG.get(), 1);
		helper.incubating(ModBlocks.SEGISAURUS_EGG.get(), ModBlocks.INCUBATED_SEGISAURUS_EGG.get(), 1);
		helper.incubating(ModBlocks.TAPEJARA_EGG.get(), ModBlocks.INCUBATED_TAPEJARA_EGG.get(), 1);
		helper.incubating(ModBlocks.TITANOSAURUS_EGG.get(), ModBlocks.INCUBATED_TITANOSAURUS_EGG.get(), 1);
		helper.incubating(ModBlocks.TROODON_EGG.get(), ModBlocks.INCUBATED_TROODON_EGG.get(), 1);
		helper.incubating(ModBlocks.TROPEOGNATHUS_EGG.get(), ModBlocks.INCUBATED_TROPEOGNATHUS_EGG.get(), 1);
		helper.incubating(ModBlocks.TUPUXUARA_EGG.get(), ModBlocks.INCUBATED_TUPUXUARA_EGG.get(), 1);
		helper.incubating(ModBlocks.UTAHRAPTOR_EGG.get(), ModBlocks.INCUBATED_UTAHRAPTOR_EGG.get(), 1);
		helper.incubating(ModBlocks.ZHENYUANOPTERUS_EGG.get(), ModBlocks.INCUBATED_ZHENYUANOPTERUS_EGG.get(), 1);
		helper.incubating(ModBlocks.ACHILLOBATOR_EGG.get(), ModBlocks.INCUBATED_ACHILLOBATOR_EGG.get(), 1);
		helper.incubating(ModBlocks.SUCHOMIMUS_EGG.get(), ModBlocks.INCUBATED_SUCHOMIMUS_EGG.get(), 1);
		helper.incubating(ModBlocks.CHILESAURUS_EGG.get(), ModBlocks.INCUBATED_CHILESAURUS_EGG.get(), 1);
		helper.incubating(ModBlocks.THESCELOSAURUS_EGG.get(), ModBlocks.INCUBATED_THESCELOSAURUS_EGG.get(), 1);
		helper.incubating(ModBlocks.MUSSASAURUS_EGG.get(), ModBlocks.INCUBATED_MUSSASAURUS_EGG.get(), 1);

		helper.amberRandomDNA(
			ModItems.TEST_TUBE.get(),
			ModItems.MOSQUITO_IN_AMBER.get(),
			ModItems.FROG_DNA.get(),
			ModItems.INDORAPTOR_DNA.get(), 0.0,
			ModItems.INDOMINUS_REX_DNA.get(), 0.0,
			ModItems.DISTORTUS_REX_DNA.get(), 0.0,
			1
		);
    }
}
